<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Basic Regression – Introduction to Statistics and Data Science</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./06-multiple-regression.html" rel="next">
<link href="./04-tidy.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-e8de9bd59ba156b9e4cb33cd6f01d621.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
  MathJax = {
    tex: {
      inlineMath: [['$', '$'], ['\\(', '\\)']]
    }
  };
  </script>
  <script id="MathJax-script" async="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js">
  </script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05-regression.html">Data Modeling</a></li><li class="breadcrumb-item"><a href="./05-regression.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Basic Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="https://statistics.northwestern.edu/" class="sidebar-logo-link">
      <img src="./images/logos/StatisticsDataScience-LogoSemi-VertPurple.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Statistics and Data Science</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/NUstat/intro-stat-data-sci" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="./Introduction-to-Statistics-and-Data-Science.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Getting started</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-getting-started.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Getting Started with Data in R</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Data Exploration via the tidyverse</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Visualization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-wrangling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Wrangling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-tidy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Importing &amp; "Tidy Data"</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Data Modeling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Basic Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-multiple-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Multiple Regression</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Statistical Theory</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-causality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Randomization and Causality</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-populations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Populations and Generalizability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-sampling-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Sampling Distributions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Statistical Inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-confidence-intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Confidence Intervals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-p-values.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">P-values</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-hypothesis-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Hypothesis tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-putting-together.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Putting it all together</span></span></a>
  </div>
</li>
          <li class="px-0"><hr class="sidebar-divider hi "></li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0a-statistical-background.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Statistical Background</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0b-solutions-exercise.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Exercise solutions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0c-solutions-learning-checks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Learning check solutions</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#packages-needed" id="toc-packages-needed" class="nav-link active" data-scroll-target="#packages-needed">Packages Needed</a></li>
  <li><a href="#sec-model1" id="toc-sec-model1" class="nav-link" data-scroll-target="#sec-model1"><span class="header-section-number">5.1</span> One numerical explanatory variable</a>
  <ul class="collapse">
  <li><a href="#sec-model1EDA" id="toc-sec-model1EDA" class="nav-link" data-scroll-target="#sec-model1EDA"><span class="header-section-number">5.1.1</span> Exploratory data analysis</a></li>
  <li><a href="#sec-model1table" id="toc-sec-model1table" class="nav-link" data-scroll-target="#sec-model1table"><span class="header-section-number">5.1.2</span> Simple linear regression</a></li>
  <li><a href="#sec-model1points" id="toc-sec-model1points" class="nav-link" data-scroll-target="#sec-model1points"><span class="header-section-number">5.1.3</span> Observed/fitted values and residuals</a></li>
  </ul></li>
  <li><a href="#sec-model2" id="toc-sec-model2" class="nav-link" data-scroll-target="#sec-model2"><span class="header-section-number">5.2</span> One categorical explanatory variable</a>
  <ul class="collapse">
  <li><a href="#sec-model2EDA" id="toc-sec-model2EDA" class="nav-link" data-scroll-target="#sec-model2EDA"><span class="header-section-number">5.2.1</span> Exploratory data analysis</a></li>
  <li><a href="#sec-model2table" id="toc-sec-model2table" class="nav-link" data-scroll-target="#sec-model2table"><span class="header-section-number">5.2.2</span> Linear regression</a></li>
  <li><a href="#sec-model2points" id="toc-sec-model2points" class="nav-link" data-scroll-target="#sec-model2points"><span class="header-section-number">5.2.3</span> Observed/fitted values and residuals</a></li>
  </ul></li>
  <li><a href="#related-topics" id="toc-related-topics" class="nav-link" data-scroll-target="#related-topics"><span class="header-section-number">5.3</span> Related topics</a>
  <ul class="collapse">
  <li><a href="#sec-correlationcoefficient" id="toc-sec-correlationcoefficient" class="nav-link" data-scroll-target="#sec-correlationcoefficient"><span class="header-section-number">5.3.1</span> Correlation coefficient</a></li>
  <li><a href="#sec-correlation-is-not-causation" id="toc-sec-correlation-is-not-causation" class="nav-link" data-scroll-target="#sec-correlation-is-not-causation"><span class="header-section-number">5.3.2</span> Correlation is not necessarily causation</a></li>
  <li><a href="#sec-leastsquares" id="toc-sec-leastsquares" class="nav-link" data-scroll-target="#sec-leastsquares"><span class="header-section-number">5.3.3</span> Best-fitting line</a></li>
  </ul></li>
  <li><a href="#sec-basic-reg-conclusion" id="toc-sec-basic-reg-conclusion" class="nav-link" data-scroll-target="#sec-basic-reg-conclusion"><span class="header-section-number">5.4</span> Conclusion</a>
  <ul class="collapse">
  <li><a href="#sec-additional-resources-basic-regression" id="toc-sec-additional-resources-basic-regression" class="nav-link" data-scroll-target="#sec-additional-resources-basic-regression"><span class="header-section-number">5.4.1</span> Additional resources</a></li>
  <li><a href="#whats-to-come" id="toc-whats-to-come" class="nav-link" data-scroll-target="#whats-to-come"><span class="header-section-number">5.4.2</span> What’s to come?</a></li>
  </ul></li>
  <li><a href="#sec-ex05" id="toc-sec-ex05" class="nav-link" data-scroll-target="#sec-ex05"><span class="header-section-number">5.5</span> Exercises</a>
  <ul class="collapse">
  <li><a href="#sec-ex05-conceptual" id="toc-sec-ex05-conceptual" class="nav-link" data-scroll-target="#sec-ex05-conceptual"><span class="header-section-number">5.5.1</span> Conceptual</a></li>
  <li><a href="#sec-ex05-application" id="toc-sec-ex05-application" class="nav-link" data-scroll-target="#sec-ex05-application"><span class="header-section-number">5.5.2</span> Application</a></li>
  <li><a href="#sec-ex05-advanced" id="toc-sec-ex05-advanced" class="nav-link" data-scroll-target="#sec-ex05-advanced"><span class="header-section-number">5.5.3</span> Advanced</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/NUstat/intro-stat-data-sci/edit/main/05-regression.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/NUstat/intro-stat-data-sci/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05-regression.html">Data Modeling</a></li><li class="breadcrumb-item"><a href="./05-regression.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Basic Regression</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-regression" class="quarto-section-identifier"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Basic Regression</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Now that we are equipped with data visualization skills from <a href="02-visualization.html" class="quarto-xref"><span>Chapter 2</span></a>, an understanding of the “tidy” data format from <a href="04-tidy.html" class="quarto-xref"><span>Chapter 4</span></a>, and data wrangling skills from <a href="03-wrangling.html" class="quarto-xref"><span>Chapter 3</span></a>, we now proceed with data modeling. The fundamental premise of data modeling is <em>to make explicit the relationship</em> between:</p>
<ul>
<li>an outcome variable <span class="math inline">\(y\)</span>, also called a dependent variable and</li>
<li>an explanatory/predictor variable <span class="math inline">\(x\)</span>, also called an independent variable or covariate.</li>
</ul>
<p>Another way to state this is using mathematical terminology: we will model the outcome variable <span class="math inline">\(y\)</span> <em>as a function</em> of the explanatory/predictor variable <span class="math inline">\(x\)</span>. Why do we have two different labels, explanatory and predictor, for the variable <span class="math inline">\(x\)</span>? That’s because roughly speaking data modeling can be used for two purposes:</p>
<ol type="1">
<li><p><strong>Modeling for prediction</strong>: You want to predict an outcome variable <span class="math inline">\(y\)</span> based on the information contained in a set of predictor variables. You don’t care so much about understanding how all the variables relate and interact, but so long as you can make good predictions about <span class="math inline">\(y\)</span>, you’re fine. For example, if we know many individuals’ risk factors for lung cancer, such as smoking habits and age, can we predict whether or not they will develop lung cancer? Here we wouldn’t care so much about distinguishing the degree to which the different risk factors contribute to lung cancer, but instead only on whether or not they could be put together to make reliable predictions.</p></li>
<li><p><strong>Modeling for explanation</strong>: You want to explicitly describe the relationship between an outcome variable <span class="math inline">\(y\)</span> and a set of explanatory variables, determine the significance of any found relationships, and have measures summarizing these. Continuing our example from above, we would now be interested in describing the individual effects of the different risk factors and quantifying the magnitude of these effects. One reason could be to design an intervention to reduce lung cancer cases in a population, such as targeting smokers of a specific age group with an advertisement for smoking cessation programs. In this book, we’ll focus more on this latter purpose.</p></li>
</ol>
<p>Data modeling is used in a wide variety of fields, including statistical inference, causal inference, artificial intelligence, and machine learning. There are many techniques for data modeling, such as tree-based models, neural networks and deep learning, and supervised learning. In this chapter, we’ll focus on one particular technique: <em>linear regression</em>, one of the most commonly-used and easy-to-understand approaches to modeling. Recall our discussion in <a href="01-getting-started.html#sec-exploredataframes" class="quarto-xref">Subsection&nbsp;<span>1.4.3</span></a> on numerical and categorical variables. Linear regression involves:</p>
<ul>
<li>an outcome variable <span class="math inline">\(y\)</span> that is <em>numerical</em> and</li>
<li>explanatory variables <span class="math inline">\(x_i\)</span> (e.g.&nbsp;<span class="math inline">\(x_1, x_2, ...\)</span>) that are either <em>numerical</em> or <em>categorical</em>.</li>
</ul>
<p>With linear regression there is always only one numerical outcome variable <span class="math inline">\(y\)</span> but we have choices on both the number and the type of explanatory variables to use. We’re going to cover the following regression scenarios:</p>
<ul>
<li>In this current chapter on basic regression, we’ll always have only one explanatory variable.
<ul>
<li>In <a href="#sec-model1" class="quarto-xref"><span>Section 5.1</span></a>, this explanatory variable will be a single numerical explanatory variable <span class="math inline">\(x\)</span>. This scenario is known as <em>simple linear regression</em>.</li>
<li>In <a href="#sec-model2" class="quarto-xref"><span>Section 5.2</span></a>, this explanatory variable will be a categorical explanatory variable <span class="math inline">\(x\)</span>.</li>
</ul></li>
<li>In the next chapter, <a href="06-multiple-regression.html" class="quarto-xref"><span>Chapter 6</span></a> on <em>multiple regression</em>, we’ll have more than one explanatory variable:
<ul>
<li>We’ll focus on two numerical explanatory variables, <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>, in <a href="06-multiple-regression.html#sec-model3" class="quarto-xref"><span>Section 6.1</span></a>.</li>
<li>We’ll use one numerical and one categorical explanatory variable in <a href="06-multiple-regression.html#sec-model3" class="quarto-xref"><span>Section 6.1</span></a>. We’ll also introduce <em>interaction models</em> here; there, the effect of one explanatory variable depends on the value of another.</li>
</ul></li>
</ul>
<p>We’ll study all four of these regression scenarios using real data, all easily accessible via R packages!</p>
<section id="packages-needed" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="packages-needed">Packages Needed</h2>
<p>Let’s now load all the packages needed for this chapter (this assumes you’ve already installed them). In this chapter we introduce some new packages:</p>
<ol type="1">
<li><p>The <code>tidyverse</code> “umbrella” package. Recall from our discussion in <a href="04-tidy.html#sec-tidyverse-package" class="quarto-xref">Subsection&nbsp;<span>4.4.1</span></a> that loading the <code>tidyverse</code> package by running <code>library(tidyverse)</code> loads the following commonly used data science packages all at once:</p>
<ul>
<li><code>ggplot2</code> for data visualization</li>
<li><code>dplyr</code> for data wrangling</li>
<li><code>tidyr</code> for converting data to “tidy” format</li>
<li><code>readr</code> for importing spreadsheet data into R</li>
<li>As well as the more advanced <code>purrr</code>, <code>tibble</code>, <code>stringr</code>, and <code>forcats</code> packages</li>
</ul></li>
<li><p>The <code>skimr</code> <span class="citation" data-cites="R-skimr">(<a href="references.html#ref-R-skimr" role="doc-biblioref">Waring et al. 2022</a>)</span> package, which provides a simple-to-use function to quickly compute a wide array of commonly-used summary statistics.</p></li>
<li><p>The <code>gapminder</code> package, which provides excerpts of data available from <a href="https://gapminder.org">Gapminder.org</a></p></li>
<li><p>The <code>moderndive</code> package, which includes datasets we will analyze</p></li>
</ol>
<p>If needed, read <a href="01-getting-started.html#sec-packages" class="quarto-xref"><span>Section 1.3</span></a> for information on how to install and load R packages.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gapminder)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(moderndive)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="sec-model1" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="sec-model1"><span class="header-section-number">5.1</span> One numerical explanatory variable</h2>
<p>Why do some professors and instructors at universities and colleges get high teaching evaluations from students while others don’t? What factors can explain these differences? Are there biases? These are questions that are of interest to university/college administrators, as teaching evaluations are among the many criteria considered in determining which professors and instructors should get promotions. Researchers at the University of Texas in Austin, Texas (UT Austin) tried to answer this question: what factors can explain differences in instructor’s teaching evaluation scores? To this end, they collected information on <span class="math inline">\(n = 463\)</span> instructors. A full description of the study can be found at <a href="https://www.openintro.org/stat/data/?data=evals">openintro.org</a>.</p>
<p>We’ll keep things simple for now and try to explain differences in instructor evaluation scores as a function of one numerical variable: their “beauty score.” The specifics on how this score was calculated will be described shortly.</p>
<p>Could it be that instructors with higher beauty scores also have higher teaching evaluations? Could it be instead that instructors with higher beauty scores tend to have lower teaching evaluations? Or could it be there is no relationship between beauty score and teaching evaluations?</p>
<p>We’ll achieve ways to address these questions by modeling the relationship between these two variables with a particular kind of linear regression called <em>simple linear regression</em>. Simple linear regression is the most basic form of linear regression. With it we have</p>
<ol type="1">
<li><p>A numerical outcome variable <span class="math inline">\(y\)</span>. In this case, an instructor’s teaching score.</p></li>
<li><p>A single numerical explanatory variable <span class="math inline">\(x\)</span>. In this case, an instructor’s beauty score.</p></li>
</ol>
<section id="sec-model1EDA" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="sec-model1EDA"><span class="header-section-number">5.1.1</span> Exploratory data analysis</h3>
<p>A crucial step before doing any kind of modeling or analysis is performing an <em>exploratory data analysis</em>, or EDA, of all our data. Exploratory data analysis can give you a sense of the distribution of the data and whether there are outliers and/or missing values. Most importantly, it can inform how to build your model. There are many approaches to exploratory data analysis; here are three:</p>
<ol type="1">
<li><p>Most fundamentally: just looking at the raw values, in a spreadsheet for example. While this may seem trivial, many people ignore this crucial step!</p></li>
<li><p>Computing summary statistics like means, medians, and standard deviations.</p></li>
<li><p>Creating data visualizations.</p></li>
</ol>
<p>Let’s load the <code>evals</code> data (which is built into the <code>moderndive</code> package), <code>select</code> only a subset of the variables, and look at the raw values. Recall you can look at the raw values by running <code>View()</code> in the console in RStudio to pop-up the spreadsheet viewer with the data frame of interest as the argument to <code>View()</code>. Here, however, we present only a snapshot of five randomly chosen rows:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>evals_ch5 <span class="ot">&lt;-</span> evals <span class="sc">%&gt;%</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(score, bty_avg, age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>evals_ch5 <span class="sc">%&gt;%</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<caption>Random sample of 5 instructors</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">score</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">bty_avg</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">age</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">3.7</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: right;">62</td>
</tr>
<tr class="even">
<td style="text-align: right;">4.7</td>
<td style="text-align: right;">4.33</td>
<td style="text-align: right;">46</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4.8</td>
<td style="text-align: right;">5.50</td>
<td style="text-align: right;">62</td>
</tr>
<tr class="even">
<td style="text-align: right;">2.8</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">62</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">2.33</td>
<td style="text-align: right;">64</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>While a full description of each of these variables can be found at <a href="https://www.openintro.org/stat/data/?data=evals">openintro.org</a>, let’s summarize what each of these variables represents.</p>
<ol type="1">
<li><p><code>score</code>: Numerical variable of the average teaching score based on students’ evaluations between 1 and 5. This is the outcome variable <span class="math inline">\(y\)</span> of interest.</p></li>
<li><p><code>bty_avg</code>: Numerical variable of average “beauty” rating based on a panel of 6 students’ scores between 1 and 10. This is the numerical explanatory variable <span class="math inline">\(x\)</span> of interest. Here 1 corresponds to a low beauty rating and 10 to a high beauty rating.</p></li>
<li><p><code>age</code>: A numerical variable of age in years as an integer value.</p></li>
</ol>
<p>An alternative way to look at the raw data values is by choosing a random sample of the rows in <code>evals_ch5</code> by piping it into the <code>slice_sample()</code> function from the <code>dplyr</code> package. Here we set the <code>n</code> argument to be <code>5</code>, indicating that we want a random sample of 5 rows. We display the results in <a href="#tbl-five-random-courses" class="quarto-xref">Table&nbsp;<span>5.1</span></a>. Note that due to the random nature of the sampling, you will likely end up with a different subset of 5 rows.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>evals_ch5 <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-five-random-courses" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-five-random-courses-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.1: A random sample of 5 out of the 463 courses at UT Austin
</figcaption>
<div aria-describedby="tbl-five-random-courses-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">score</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">bty_avg</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">age</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">4.4</td>
<td style="text-align: right;">5.67</td>
<td style="text-align: right;">57</td>
</tr>
<tr class="even">
<td style="text-align: right;">3.1</td>
<td style="text-align: right;">7.00</td>
<td style="text-align: right;">33</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4.1</td>
<td style="text-align: right;">4.17</td>
<td style="text-align: right;">45</td>
</tr>
<tr class="even">
<td style="text-align: right;">5.0</td>
<td style="text-align: right;">4.33</td>
<td style="text-align: right;">46</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4.8</td>
<td style="text-align: right;">4.83</td>
<td style="text-align: right;">52</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Now that we’ve looked at the raw values in our <code>evals_ch5</code> data frame and got a preliminary sense of the data, let’s move on to the next common step in an exploratory data analysis: computing summary statistics. Let’s start by computing the mean and median of our numerical outcome variable <code>score</code> and our numerical explanatory variable “beauty” score denoted as <code>bty_avg</code>. We’ll do this by using the <code>summarize()</code> function from <code>dplyr</code> along with the <code>mean()</code> and <code>median()</code> summary functions we saw in <a href="03-wrangling.html#sec-summarize" class="quarto-xref"><span>Section 3.3</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>evals_ch5 <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_bty_avg =</span> <span class="fu">mean</span>(bty_avg),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_score =</span> <span class="fu">mean</span>(score),</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_bty_avg =</span> <span class="fu">median</span>(bty_avg), </span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_score =</span> <span class="fu">median</span>(score)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  mean_bty_avg mean_score median_bty_avg median_score
         &lt;dbl&gt;      &lt;dbl&gt;          &lt;dbl&gt;        &lt;dbl&gt;
1         4.42       4.17           4.33          4.3</code></pre>
</div>
</div>
<p>However, what if we want other summary statistics as well, such as the standard deviation (a measure of spread), the minimum and maximum values, and various percentiles? Typing out all these summary statistic functions in <code>summarize()</code> would be long and tedious. Instead, let’s use the convenient <code>skim()</code> function from the <code>skimr</code> package. This function takes in a data frame, “skims” it, and returns commonly used summary statistics. Let’s take our <code>evals_ch5</code> data frame, <code>select()</code> only the outcome and explanatory variables teaching <code>score</code> and <code>bty_avg</code>, and pipe them into the <code>skim()</code> function:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>evals_ch5 <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(score, bty_avg) <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">skim</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<pre><code>── Data Summary ────────────────────────
                           Values    
Name                       Piped data
Number of rows             463       
Number of columns          2         
_______________________              
Column type frequency:               
  numeric                  2         
________________________             
Group variables            None      

── Variable type: numeric ──────────────────────────────────────────────────────
  skim_variable n_missing complete_rate mean    sd   p0  p25  p50 p75 p100 hist 
1 score                 0             1 4.17 0.544 2.3  3.8  4.3  4.6 5    ▁▁▅▇▇
2 bty_avg               0             1 4.42 1.53  1.67 3.17 4.33 5.5 8.17 ▃▇▇▃▂ </code></pre>
<p>For our two numerical variables teaching <code>score</code> and “beauty” score <code>bty_avg</code> it returns:</p>
<ul>
<li><code>n_missing</code>: the number of missing values</li>
<li><code>complete_rate</code>: the proportion of non-missing or complete values</li>
<li><code>mean</code>: the average</li>
<li><code>sd</code>: the standard deviation</li>
<li><code>p0</code>: the 0<sup>th</sup> percentile: the value at which 0% of observations are smaller than it (the <em>minimum</em> value)</li>
<li><code>p25</code>: the 25<sup>th</sup> percentile: the value at which 25% of observations are smaller than it (the <em>1<sup>st</sup> quartile</em>)</li>
<li><code>p50</code>: the 50<sup>th</sup> percentile: the value at which 50% of observations are smaller than it (the <em>2<sup>nd</sup></em> quartile and more commonly called the <em>median</em>)</li>
<li><code>p75</code>: the 75<sup>th</sup> percentile: the value at which 75% of observations are smaller than it (the <em>3<sup>rd</sup> quartile</em>)</li>
<li><code>p100</code>: the 100<sup>th</sup> percentile: the value at which 100% of observations are smaller than it (the <em>maximum</em> value)</li>
</ul>
<p>Looking at this output, we get an idea of how the values of both variables distribute. For example, the mean teaching score was 4.17 out of 5 whereas the mean “beauty” score was 4.42 out of 10. Furthermore, the middle 50% of teaching scores were between 3.80 and 4.6 (the first and third quartiles) whereas the middle 50% of “beauty” scores were between 3.17 and 5.5 out of 10.</p>
<p>The <code>skim()</code> function only returns what are known as <em>univariate</em> summary statistics: functions that take a single variable and return some numerical summary of that variable. However, there also exist <em>bivariate</em> summary statistics: functions that take in two variables and return some summary of those two variables. In particular, when the two variables are numerical, we can compute the <em>correlation coefficient</em>. Generally speaking, <em>coefficients</em> are quantitative expressions of a specific phenomenon. A <em>correlation coefficient</em> is a quantitative expression of the <em>strength of the linear relationship between two numerical variables</em>. Its value ranges between -1 and 1 where:</p>
<ul>
<li>-1 indicates a perfect <em>negative relationship</em>: As the value of one variable goes up, the value of the other variable tends to go down following along a straight line.</li>
<li>0 indicates no relationship: The values of both variables go up/down independently of each other.</li>
<li>+1 indicates a perfect <em>positive relationship</em>: As the value of one variable goes up, the value of the other variable tends to go up as well in a linear fashion.</li>
</ul>
<p><a href="#fig-correlation1" class="quarto-xref">Figure&nbsp;<span>5.1</span></a> gives examples of different correlation coefficient values for hypothetical numerical variables <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>. We see that while for a correlation coefficient of -0.75 there is still a negative relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>, it is not as strong as the negative relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> when the correlation coefficient is -1.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-correlation1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-correlation1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-regression_files/figure-html/fig-correlation1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-correlation1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.1: Different correlation coefficients
</figcaption>
</figure>
</div>
</div>
</div>
<p>The correlation coefficient is computed using the <code>cor()</code> function, where the inputs to the function are the two numerical variables for which we want to quantify the strength of the linear relationship.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>evals_ch5 <span class="sc">%&gt;%</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">correlation =</span> <span class="fu">cor</span>(score, bty_avg))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  correlation
        &lt;dbl&gt;
1       0.187</code></pre>
</div>
</div>
<p>You can also use the <code>cor()</code> function directly instead of using it inside <code>summarise</code>, but you will need to use the <code>$</code> syntax to access the specific variables within a data frame (See <a href="01-getting-started.html#sec-exploredataframes" class="quarto-xref">Subsection&nbsp;<span>1.4.3</span></a>):</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(<span class="at">x =</span> evals_ch5<span class="sc">$</span>bty_avg, <span class="at">y =</span> evals_ch5<span class="sc">$</span>score)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.187</code></pre>
</div>
</div>
<p>In our case, the correlation coefficient of 0.187 indicates that the relationship between teaching evaluation score and beauty average is “weakly positive.” There is a certain amount of subjectivity in interpreting correlation coefficients, especially those that aren’t close to -1, 0, and 1. For help developing such intuition and more discussion on the correlation coefficient see [Subsection <a href="#sec-correlationcoefficient" class="quarto-xref"><span>5.3.1</span></a> below.</p>
<p>Let’s now proceed by visualizing this data. Since both the <code>score</code> and <code>bty_avg</code> variables are numerical, a scatterplot is an appropriate graph to visualize this data. Let’s do this using <code>geom_point()</code> and set informative axes labels and title and display the result in <a href="#fig-numxplot1" class="quarto-xref">Figure&nbsp;<span>5.2</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(evals_ch5, <span class="fu">aes</span>(<span class="at">x =</span> bty_avg, <span class="at">y =</span> score)) <span class="sc">+</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Beauty Score"</span>, <span class="at">y =</span> <span class="st">"Teaching Score"</span>, </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Relationship of teaching and beauty scores"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-numxplot1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-numxplot1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-regression_files/figure-html/fig-numxplot1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-numxplot1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.2: Instructor evaluation scores at UT Austin
</figcaption>
</figure>
</div>
</div>
</div>
<p>Observe the following:</p>
<ol type="1">
<li><p>Most “beauty” scores lie between 2 and 8.</p></li>
<li><p>Most teaching scores lie between 3 and 5.</p></li>
<li><p>Recall our earlier computation of the correlation coefficient, which describes the strength of the linear relationship between two numerical variables. Looking at <a href="#fig-numxplot2" class="quarto-xref">Figure&nbsp;<span>5.3</span></a>, it is not immediately apparent that these two variables are positively related. This is to be expected given the positive, but rather weak (close to 0), correlation coefficient of 0.187.</p></li>
</ol>
<p>Before we continue, we bring to light an important fact about this dataset: it suffers from <em>overplotting</em>. Recall from the data visualization <a href="02-visualization.html#sec-overplotting" class="quarto-xref">Subsection&nbsp;<span>2.3.2</span></a> that overplotting occurs when several points are stacked directly on top of each other thereby obscuring the number of points. For example, let’s focus on the 6 points in the top-right of the plot with a beauty score of around 8 out of 10: are there truly only 6 points, or are there many more just stacked on top of each other? You can think of these as <em>ties</em>. Let’s break up these ties with a little random “jitter” added to the points in <a href="#fig-numxplot2" class="quarto-xref">Figure&nbsp;<span>5.3</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-numxplot2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-numxplot2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-regression_files/figure-html/fig-numxplot2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-numxplot2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.3: Instructor evaluation scores at UT Austin: Jittered
</figcaption>
</figure>
</div>
</div>
</div>
<p>Jittering adds a little random bump to each of the points to break up these ties: just enough so you can distinguish them, but not so much that the plot is overly altered. Furthermore, jittering is strictly a visualization tool; it does not alter the original values in the dataset.</p>
<p>Let’s compare side-by-side the regular scatterplot in <a href="#fig-numxplot1" class="quarto-xref">Figure&nbsp;<span>5.2</span></a> with the jittered scatterplot <a href="#fig-numxplot2" class="quarto-xref">Figure&nbsp;<span>5.3</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-numxplot2-a" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-numxplot2-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-regression_files/figure-html/fig-numxplot2-a-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-numxplot2-a-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.4: Comparing regular and jittered scatterplots
</figcaption>
</figure>
</div>
</div>
</div>
<p>We make several further observations:</p>
<ol type="1">
<li><p>Focusing our attention on the top-right of the plot again, as noted earlier where there seemed to only be 6 points in the regular scatterplot, we see there were in fact really 9 as seen in the jittered scatterplot.</p></li>
<li><p>A further interesting trend is that the jittering revealed a large number of instructors with beauty scores of between 3 and 4.5, towards the lower end of the beauty scale.</p></li>
</ol>
<p>To keep things simple in this chapter, we’ll present regular scatterplots rather than the jittered scatterplots, though we’ll keep the overplotting in mind whenever looking at such plots. Going back to scatterplot in <a href="#fig-numxplot1" class="quarto-xref">Figure&nbsp;<span>5.2</span></a>, let’s improve on it by adding a “regression line” in <a href="#fig-numxplot3" class="quarto-xref">Figure&nbsp;<span>5.5</span></a>. This is easily done by adding a new layer to the <code>ggplot</code> code that created <a href="#fig-numxplot2" class="quarto-xref">Figure&nbsp;<span>5.3</span></a>: <code>+ geom_smooth(method = "lm")</code>. A regression line is a “best fitting” line in that of all possible lines you could draw on this plot, it is “best” in terms of some mathematical criteria. We discuss the criteria for “best” in <a href="#sec-leastsquares" class="quarto-xref">Subsection&nbsp;<span>5.3.3</span></a> below, but we suggest you read this only after covering the concept of a <em>residual</em> coming up in <a href="#sec-model1points" class="quarto-xref">Subsection&nbsp;<span>5.1.3</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(evals_ch5, <span class="fu">aes</span>(<span class="at">x =</span> bty_avg, <span class="at">y =</span> score)) <span class="sc">+</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Beauty Score"</span>, </span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Teaching Score"</span>, </span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Relationship of teaching and beauty scores"</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span>  </span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-numxplot3" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-numxplot3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-regression_files/figure-html/fig-numxplot3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-numxplot3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.5: Regression line
</figcaption>
</figure>
</div>
</div>
</div>
<p>When viewed on this plot, the regression line is a visual summary of the relationship between two numerical variables, in our case the outcome variable <code>score</code> and the explanatory variable <code>bty_avg</code>. The positive slope of the blue line is consistent with our observed correlation coefficient of 0.187 suggesting that there is a positive relationship between <code>score</code> and <code>bty_avg</code>. We’ll see later however that while the correlation coefficient is not equal to the slope of this line, they always have the same sign: positive or negative.</p>
<p>What are the grey bands surrounding the blue line? These are <em>standard error</em> bands, which can be thought of as error/uncertainty bands. Let’s skip this idea for now and suppress these grey bars by adding the argument <code>se = FALSE</code> to <code>geom_smooth(method = "lm")</code>. We’ll introduce standard errors when covering sampling distributions (<a href="09-sampling-distributions.html" class="quarto-xref"><span>Chapter 9</span></a>). We also will use standard errors to construct <em>confidence intervals</em> (<a href="10-confidence-intervals.html" class="quarto-xref"><span>Chapter 10</span></a>) and conduct <em>hypothesis tests</em> (<a href="12-hypothesis-tests.html" class="quarto-xref"><span>Chapter 12</span></a>). Standard errors are really important!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(evals_ch5, <span class="fu">aes</span>(<span class="at">x =</span> bty_avg, <span class="at">y =</span> score)) <span class="sc">+</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Beauty Score"</span>, </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Teaching Score"</span>, </span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Relationship of teaching and beauty scores"</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">+</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-numxplot4" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-numxplot4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-regression_files/figure-html/fig-numxplot4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-numxplot4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.6: Regression line without error bands
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="emoji" data-emoji="dart">🎯</span> Learning Check 5.1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Conduct a new exploratory data analysis with the same outcome variable <span class="math inline">\(y\)</span> being <code>score</code> but with <code>age</code> as the new explanatory variable <span class="math inline">\(x\)</span>. Remember, this involves three things:</p>
<ol type="a">
<li>Looking at the raw values.</li>
<li>Computing summary statistics of the variables of interest.</li>
<li>Creating informative visualizations.</li>
</ol>
<p>What can you say about the relationship between age and teaching scores based on this exploration?</p>
</div>
</div>
</div>
</section>
<section id="sec-model1table" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="sec-model1table"><span class="header-section-number">5.1.2</span> Simple linear regression</h3>
<p>You may recall from secondary school / high school algebra, in general, the equation of a line is <span class="math inline">\(y = a + bx\)</span>, which is defined by two coefficients. Recall we defined this earlier as “quantitative expressions of a specific property of a phenomenon.” These two coefficients are:</p>
<ul>
<li>the intercept coefficient <span class="math inline">\(a\)</span>, or the value of <span class="math inline">\(y\)</span> when <span class="math inline">\(x = 0\)</span>, and</li>
<li>the slope coefficient <span class="math inline">\(b\)</span>, or the increase in <span class="math inline">\(y\)</span> for every increase of one in <span class="math inline">\(x\)</span>.</li>
</ul>
<p>However, when defining a line specifically for regression, like the blue regression line in <a href="#fig-numxplot4" class="quarto-xref">Figure&nbsp;<span>5.6</span></a>, we use slightly different notation: the equation of the regression line is <span class="math inline">\(\widehat{y} = b_0 + b_1 \cdot x\)</span> where</p>
<ul>
<li>the intercept coefficient is <span class="math inline">\(b_0\)</span>, or the value of <span class="math inline">\(\widehat{y}\)</span> when <span class="math inline">\(x=0\)</span>, and</li>
<li>the slope coefficient <span class="math inline">\(b_1\)</span>, or the increase in <span class="math inline">\(\widehat{y}\)</span> for every increase of one in <span class="math inline">\(x\)</span>.</li>
</ul>
<p>Why do we put a “hat” on top of the <span class="math inline">\(y\)</span>? It’s a form of notation commonly used in regression, which we’ll introduce in the next <a href="#sec-model1points" class="quarto-xref">Subsection&nbsp;<span>5.1.3</span></a> when we discuss <em>fitted values</em>. For now, let’s ignore the hat and treat the equation of the line as you would from secondary school / high school algebra recognizing the slope and the intercept. We know looking at <a href="#fig-numxplot4" class="quarto-xref">Figure&nbsp;<span>5.6</span></a> that the slope coefficient corresponding to <code>bty_avg</code> should be positive. Why? Because as <code>bty_avg</code> increases, professors tend to roughly have higher teaching evaluation <code>scores</code>. However, what are the specific values of the intercept and slope coefficients? Let’s not worry about computing these by hand, but instead let the computer do the work for us. Specifically, let’s use R!</p>
<p>Let’s get the value of the intercept and slope coefficients by outputting something called the <em>linear regression table</em>. We will fit the linear regression model to the <code>data</code> using the <code>lm()</code> function and save this to <code>score_model</code>. <code>lm</code> stands for “linear model.” When we say “fit”, we are saying find the best fitting line to this data.</p>
<p>The <code>lm()</code> function that “fits” the linear regression model is typically used as <code>lm(y ~ x, data = data_frame_name)</code> where:</p>
<ul>
<li><p><code>y</code> is the outcome variable, followed by a tilde (<code>~</code>). This is likely the key to the left of “1” on your keyboard. In our case, <code>y</code> is set to <code>score</code>.</p></li>
<li><p><code>x</code> is the explanatory variable. In our case, <code>x</code> is set to <code>bty_avg</code>. We call the combination <code>y ~ x</code> a <em>model formula</em>.</p></li>
<li><p><code>data_frame_name</code> is the name of the data frame that contains the variables <code>y</code> and <code>x</code>. In our case, <code>data_frame_name</code> is the <code>evals_ch5</code> data frame.</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>score_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(score <span class="sc">~</span> bty_avg, <span class="at">data =</span> evals_ch5)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>score_model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = score ~ bty_avg, data = evals_ch5)

Coefficients:
(Intercept)      bty_avg  
     3.8803       0.0666  </code></pre>
</div>
</div>
<p>This output is telling us that the <code>Intercept</code> coefficient <span class="math inline">\(b_0\)</span> of the regression line is 3.8803, and the slope coefficient for <code>by_avg</code> is 0.0666. Therefore the blue regression line in <a href="#fig-numxplot4" class="quarto-xref">Figure&nbsp;<span>5.6</span></a> is</p>
<p><span class="math display">\[\widehat{\text{score}} = b_0 + b_{\text{bty avg}} \cdot\text{bty avg} = 3.8803 + 0.0666\cdot\text{bty avg}\]</span></p>
<p>where</p>
<ul>
<li><p>The intercept coefficient <span class="math inline">\(b_0 = 3.8803\)</span> means for instructors that had a hypothetical beauty score of 0, we would expect them to have on average a teaching score of 3.8803. In this case however, while the intercept has a mathematical interpretation when defining the regression line, there is no <em>practical</em> interpretation since <code>score</code> is an average of a panel of 6 students’ ratings from 1 to 10, a <code>bty_avg</code> of 0 would be impossible. Furthermore, no instructors had a beauty score anywhere near 0 in this data.</p></li>
<li><p>Of more interest is the slope coefficient associated with <code>bty_avg</code>: <span class="math inline">\(b_{\text{bty avg}} = +0.0666\)</span>. This is a numerical quantity that summarizes the relationship between the outcome and explanatory variables. Note that the sign is positive, suggesting a positive relationship between beauty scores and teaching scores, meaning as beauty scores go up, so also do teaching scores go up. The slope’s precise interpretation is:</p></li>
</ul>
<blockquote class="blockquote">
<p>For every increase of 1 unit in <code>bty_avg</code>, there is an <em>associated</em> increase of, <em>on average</em>, 0.0666 units of <code>score</code>.</p>
</blockquote>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Such interpretations need be carefully worded:</strong></p>
<ul>
<li><p>We only stated that there is an <em>associated</em> increase, and not necessarily a <em>causal</em> increase. For example, perhaps it’s not that beauty directly affects teaching scores, but instead younger instructors tend to be perceived as better teachers (perhaps because they are more energetic or use more modern techniques), and younger instructors are also perceived to be more beautiful. Avoiding such reasoning can be summarized by the adage “correlation is not necessarily causation.” In other words, just because two variables are correlated, it doesn’t mean one directly causes the other. We discuss these ideas more in <a href="#sec-correlation-is-not-causation" class="quarto-xref">Subsection&nbsp;<span>5.3.2</span></a> and in <a href="07-causality.html" class="quarto-xref"><span>Chapter 7</span></a>.</p></li>
<li><p>We say that this associated increase is <em>on average</em> 0.0666 units of teaching <code>score</code> and not that the associated increase is <em>exactly</em> 0.0666 units of <code>score</code> across all values of <code>bty_avg</code>. This is because the slope is the average increase across all points as shown by the regression line in <a href="#fig-numxplot4" class="quarto-xref">Figure&nbsp;<span>5.6</span></a>.</p></li>
</ul>
</div>
</div>
<p>Now that we’ve learned how to compute the equation for the blue regression line in <a href="#fig-numxplot4" class="quarto-xref">Figure&nbsp;<span>5.6</span></a> and interpreted all its terms, let’s take our modeling one step further. This time after fitting the model using the <code>lm()</code>, let’s get something called the <em>regression table</em> using the <code>summary()</code> function:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit regression model:</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>score_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(score <span class="sc">~</span> bty_avg, <span class="at">data =</span> evals_ch5)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Get regression results:</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(score_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = score ~ bty_avg, data = evals_ch5)

Residuals:
   Min     1Q Median     3Q    Max 
-1.925 -0.369  0.142  0.398  0.931 

Coefficients:
            Estimate Std. Error t value             Pr(&gt;|t|)    
(Intercept)   3.8803     0.0761   50.96 &lt; 0.0000000000000002 ***
bty_avg       0.0666     0.0163    4.09             0.000051 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.535 on 461 degrees of freedom
Multiple R-squared:  0.035, Adjusted R-squared:  0.0329 
F-statistic: 16.7 on 1 and 461 DF,  p-value: 0.0000508</code></pre>
</div>
</div>
<p>Note how we took the output of the model fit saved in <code>score_model</code> and used it as an input to the subsequent <code>summary()</code> function. The raw output of the <code>summary()</code> function above gives lots of information about the regression model that we won’t cover in this introductory course (e.g., Multiple R-squared, F-statistic, etc.). We will only consider the “Coefficients” section of the output. We can print these relevant results only by accessing the <code>coefficients</code> object stored in the summary results.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(score_model)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-numxplot4b" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-numxplot4b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.2: Linear regression table
</figcaption>
<div aria-describedby="tbl-numxplot4b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Std. Error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">3.880</td>
<td style="text-align: right;">0.076</td>
<td style="text-align: right;">50.96</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">bty_avg</td>
<td style="text-align: right;">0.067</td>
<td style="text-align: right;">0.016</td>
<td style="text-align: right;">4.09</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>For now since we are only using regression as an exploratory data analysis tool, we will only focus on the “Estimate” column that contains the estimates of the intercept and slope for the best fit line for our data. The remaining three columns refer to statistical concepts known as standard errors, t-statistics, and p-values, which we will cover in Parts III and IV of the book when we talk about statistical theory and inference.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="emoji" data-emoji="dart">🎯</span> Learning Check 5.2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Fit a new simple linear regression using <code>lm(score ~ age, data = evals_ch5)</code> where <code>age</code> is the new explanatory variable <span class="math inline">\(x\)</span>. Get information about the “best-fitting” line from the regression table by applying the <code>summary()</code> function. How do the regression results match up with the results from your exploratory data analysis above?</p>
</div>
</div>
</div>
</section>
<section id="sec-model1points" class="level3" data-number="5.1.3">
<h3 data-number="5.1.3" class="anchored" data-anchor-id="sec-model1points"><span class="header-section-number">5.1.3</span> Observed/fitted values and residuals</h3>
<p>We just saw how to get the value of the intercept and the slope of the regression line from the regression table generated by <code>summary()</code>. Now instead, say we want information on individual points. In this case, we focus on one of the <span class="math inline">\(n = 463\)</span> instructors in this dataset, corresponding to a single row of <code>evals_ch5</code>.</p>
<p>For example, say we are interested in the 21st instructor in this dataset:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<caption>Data for 21st instructor</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">score</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">bty_avg</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">age</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">4.9</td>
<td style="text-align: right;">7.33</td>
<td style="text-align: right;">31</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>What is the value on the blue line corresponding to this instructor’s <code>bty_avg</code> of 7.333? In <a href="#fig-numxplot5" class="quarto-xref">Figure&nbsp;<span>5.7</span></a> we mark three values in particular corresponding to this instructor.</p>
<ul>
<li><p>Red circle: This is the <em>observed value</em> <span class="math inline">\(y\)</span> = 4.9 and corresponds to this instructor’s actual teaching score.</p></li>
<li><p>Red square: This is the <em>fitted value</em> <span class="math inline">\(\widehat{y}\)</span> and corresponds to the value on the regression line for <span class="math inline">\(x\)</span> = 7.333. This value is computed using the intercept and slope in the regression table above:</p></li>
</ul>
<p><span class="math display">\[\widehat{y} = b_0 + b_1 \cdot x = 3.88 + 0.067 * 7.333 = 4.369\]</span></p>
<ul>
<li>Blue arrow: The length of this arrow is the <em>residual</em> and is computed by subtracting the fitted value <span class="math inline">\(\widehat{y}\)</span> from the observed value <span class="math inline">\(y\)</span>. The residual can be thought of as the error or “lack of fit” of the regression line. In the case of this instructor, it is <span class="math inline">\(y - \widehat{y}\)</span> = 4.9 - 4.369 = 0.531. In other words, the model was off by 0.531 teaching score units for this instructor.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-numxplot5" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-numxplot5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-regression_files/figure-html/fig-numxplot5-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-numxplot5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.7: Example of observed value, fitted value, and residual
</figcaption>
</figure>
</div>
</div>
</div>
<p>What if we want both</p>
<ol type="1">
<li>the fitted value <span class="math inline">\(\widehat{y} = b_0 + b_1 \cdot x\)</span> and</li>
<li>the residual <span class="math inline">\(y - \widehat{y}\)</span></li>
</ol>
<p>for not only the 21st instructor but for all 463 instructors in the study? Recall that each instructor corresponds to one of the 463 rows in the <code>evals_ch5</code> data frame and also one of the 463 points in the regression plot in <a href="#fig-numxplot4" class="quarto-xref">Figure&nbsp;<span>5.6</span></a>.</p>
<p>We could repeat the above calculations by hand 463 times, but that would be tedious and time consuming. Instead, let’s use our data wrangling tools from <a href="03-wrangling.html" class="quarto-xref"><span>Chapter 3</span></a> and the functions <code>fitted()</code> and <code>residuals()</code> to create a data frame with these values. Similar to the <code>summary()</code> function, the <code>fitted()</code> and <code>residuals()</code> functions also take a model object as their input. <code>fitted()</code> calculates all the <em>fitted</em> <span class="math inline">\(\hat{y}\)</span> values by plugging in each observed <span class="math inline">\(x\)</span> value in the dataset into the regression equation, and <code>residuals()</code> similarly calculates all the residuals (<span class="math inline">\(y - \hat{y}\)</span>) for each observation in the dataset. The following code will store these new <span class="math inline">\(\hat{y}\)</span> and residual variables, which we will name <code>score_hat</code> and <code>residual</code> respectively, along with their corresponding <code>score</code> and <code>bty_avg</code> values from the original data <code>evals_ch5</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>score_model_data <span class="ot">&lt;-</span> evals_ch5 <span class="sc">%&gt;%</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(score, bty_avg) <span class="sc">%&gt;%</span> </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">score_hat =</span> <span class="fu">fitted</span>(score_model),</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">residual =</span> <span class="fu">residuals</span>(score_model)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span> </span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rownames_to_column</span>(<span class="st">"ID"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that we also used the <code>rownames_to_column()</code> function from the <code>tibble</code> package (part of the <code>tidyverse</code> suite) to create a convenient ID column from the rownames. In the table below we only present the results for the 21st through the 24th instructors.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-reg-points" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-reg-points-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.3: Regression points (for only 21st through 24th instructor)
</figcaption>
<div aria-describedby="tbl-reg-points-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">ID</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">score</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">bty_avg</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">score_hat</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">residual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">21</td>
<td style="text-align: right;">4.9</td>
<td style="text-align: right;">7.33</td>
<td style="text-align: right;">4.37</td>
<td style="text-align: right;">0.531</td>
</tr>
<tr class="even">
<td style="text-align: right;">22</td>
<td style="text-align: right;">4.6</td>
<td style="text-align: right;">7.33</td>
<td style="text-align: right;">4.37</td>
<td style="text-align: right;">0.231</td>
</tr>
<tr class="odd">
<td style="text-align: right;">23</td>
<td style="text-align: right;">4.5</td>
<td style="text-align: right;">7.33</td>
<td style="text-align: right;">4.37</td>
<td style="text-align: right;">0.131</td>
</tr>
<tr class="even">
<td style="text-align: right;">24</td>
<td style="text-align: right;">4.4</td>
<td style="text-align: right;">5.50</td>
<td style="text-align: right;">4.25</td>
<td style="text-align: right;">0.153</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Let’s recap what we’re seeing in <a href="#tbl-reg-points" class="quarto-xref">Table&nbsp;<span>5.3</span></a> in terms of the linear regression model (<code>score_model</code>) that we fit to the <code>evals_ch5</code> data:</p>
<ul>
<li><p>The <code>ID</code> column represents the row number where this observation appears in the original <code>evals_ch5</code> data</p></li>
<li><p>The <code>score</code> column represents the observed value of the outcome variable <span class="math inline">\(y\)</span>.</p></li>
<li><p>The <code>bty_avg</code> column represents the values of the explanatory variable <span class="math inline">\(x\)</span>.</p></li>
<li><p>The <code>score_hat</code> column represents the fitted values <span class="math inline">\(\widehat{y}\)</span>.</p></li>
<li><p>The <code>residual</code> column represents the residuals <span class="math inline">\(y - \widehat{y}\)</span>.</p></li>
</ul>
<p>Just as we did for the 21st instructor in the <code>evals_ch5</code> dataset (in the first row of the table above), let’s repeat the above calculations for the 24th instructor in the <code>evals_ch5</code> dataset (in the fourth row of the table above):</p>
<ul>
<li><p><code>score</code> = 4.4 is the observed value <span class="math inline">\(y\)</span> for this instructor.</p></li>
<li><p><code>bty_avg</code> = 5.50 is the value of the explanatory variable <span class="math inline">\(x\)</span> for this instructor.</p></li>
<li><p><code>score_hat</code> = 4.25 = 3.88 + 0.067 * <span class="math inline">\(x\)</span> = 3.88 + 0.067 * 5.50 is the fitted value <span class="math inline">\(\widehat{y}\)</span> for this instructor.</p></li>
<li><p><code>residual</code> = 0.153 = 4.4 - 4.25 is the value of the residual for this instructor. In other words, the model was off by 0.153 teaching score units for this instructor.</p></li>
</ul>
<p>More development of this idea appears in <a href="#sec-leastsquares" class="quarto-xref">Subsection&nbsp;<span>5.3.3</span></a> and we encourage you to read that section after you investigate residuals.</p>
</section>
</section>
<section id="sec-model2" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="sec-model2"><span class="header-section-number">5.2</span> One categorical explanatory variable</h2>
<p>It’s an unfortunate truth that life expectancy is not the same across various countries in the world; there are a multitude of factors that are associated with how long people live. International development agencies are very interested in studying these differences in the hope of understanding where governments should allocate resources to address this problem. In this section, we’ll explore differences in life expectancy in two ways:</p>
<ol type="1">
<li><p>Differences between continents: Are there significant differences in life expectancy, on average, between the five continents of the world: Africa, the Americas, Asia, Europe, and Oceania?</p></li>
<li><p>Differences within continents: How does life expectancy vary within the world’s five continents? For example, is the spread of life expectancy among the countries of Africa larger than the spread of life expectancy among the countries of Asia?</p></li>
</ol>
<p>To answer such questions, we’ll study the <code>gapminder</code> dataset from the <code>gapminder</code> package. Recall we mentioned this dataset in <a href="02-visualization.html#sec-gapminder" class="quarto-xref">Subsection&nbsp;<span>2.1.2</span></a> when we first introduced the “Grammar of Graphics” (<a href="02-visualization.html" class="quarto-xref"><span>Chapter 2</span></a>). This dataset has international development statistics such as life expectancy, GDP per capita, and population by country (<span class="math inline">\(n\)</span> = 142) for 5-year intervals between 1952 and 2007.</p>
<p>We’ll use this data for linear regression again, but note that our explanatory variable <span class="math inline">\(x\)</span> is now categorical, and not numerical like when we covered simple linear regression in <a href="#sec-model1" class="quarto-xref"><span>Section 5.1</span></a>. More precisely, we have:</p>
<ol type="1">
<li><p>A numerical outcome variable <span class="math inline">\(y\)</span>. In this case, life expectancy.</p></li>
<li><p>A single categorical explanatory variable <span class="math inline">\(x\)</span>. In this case, the continent the country is part of.</p></li>
</ol>
<p>When the explanatory variable <span class="math inline">\(x\)</span> is categorical, the concept of a “best-fitting” line is a little different than the one we saw previously in <a href="#sec-model1" class="quarto-xref"><span>Section 5.1</span></a> where the explanatory variable <span class="math inline">\(x\)</span> was numerical. We’ll study these differences shortly in [Subsection <a href="#sec-model2table" class="quarto-xref"><span>5.2.2</span></a>, but first we conduct our exploratory data analysis.</p>
<section id="sec-model2EDA" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="sec-model2EDA"><span class="header-section-number">5.2.1</span> Exploratory data analysis</h3>
<p>The data on the 142 countries can be found in the <code>gapminder</code> data frame included in the <code>gapminder</code> package. However, to keep things simple, let’s <code>filter()</code> for only those observations/rows corresponding to the year 2007. Additionally, let’s <code>select()</code> only the subset of the variables we’ll consider in this chapter. We’ll save this data in a new data frame called <code>gapminder2007</code>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gapminder)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>gapminder2007 <span class="ot">&lt;-</span> gapminder <span class="sc">%&gt;%</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2007</span>) <span class="sc">%&gt;%</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(country, lifeExp, continent, gdpPercap)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Recall from <a href="#sec-model1EDA" class="quarto-xref"><span>Section 5.1.1</span></a> that there are three common steps in an exploratory data analysis:</p>
<ol type="1">
<li><p>Most crucially: Looking at the raw data values.</p></li>
<li><p>Computing summary statistics, like means, medians, and interquartile ranges.</p></li>
<li><p>Creating data visualizations.</p></li>
</ol>
<p>Let’s perform the first common step in an exploratory data analysis: looking at the raw data values. You can do this by using RStudio’s spreadsheet viewer or by using the <code>glimpse()</code> command as introduced in <a href="01-getting-started.html#sec-exploredataframes" class="quarto-xref"><span>Section 1.4.3</span></a> on exploring data frames:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(gapminder2007)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 142
Columns: 4
$ country   &lt;fct&gt; "Afghanistan", "Albania", "Algeria", "Angola", "Argentina", …
$ lifeExp   &lt;dbl&gt; 43.8, 76.4, 72.3, 42.7, 75.3, 81.2, 79.8, 75.6, 64.1, 79.4, …
$ continent &lt;fct&gt; Asia, Europe, Africa, Africa, Americas, Oceania, Europe, Asi…
$ gdpPercap &lt;dbl&gt; 975, 5937, 6223, 4797, 12779, 34435, 36126, 29796, 1391, 336…</code></pre>
</div>
</div>
<p>Observe that <code>Observations: 142</code> indicates that there are 142 rows/observations in <code>gapminder2007</code>, where each row corresponds to one country. In other words, the <em>observational unit</em> is an individual country. Furthermore, observe that the variable <code>continent</code> is of type <code>&lt;fct&gt;</code>, which stands for <em>factor</em>, which is R’s way of encoding categorical variables.</p>
<p>A full description of all the variables included in <code>gapminder</code> can be found by reading the associated help file (run <code>?gapminder</code> in the console). However, let’s fully describe the 4 variables we selected in <code>gapminder2007</code>:</p>
<ol type="1">
<li><p><code>country</code>: An identification text variable used to distinguish the 142 countries in the dataset.</p></li>
<li><p><code>lifeExp</code>: A numerical variable of that country’s life expectancy at birth. This is the outcome variable <span class="math inline">\(y\)</span> of interest.</p></li>
<li><p><code>continent</code>: A categorical variable with five levels. Here “levels” corresponds to the possible categories: Africa, Asia, Americas, Europe, and Oceania. This is the explanatory variable <span class="math inline">\(x\)</span> of interest.</p></li>
<li><p><code>gdpPercap</code>: A numerical variable of that country’s GDP per capita in US inflation-adjusted dollars that we’ll use as another outcome variable <span class="math inline">\(y\)</span> in the Learning Check at the end of this subsection.</p></li>
</ol>
<p>Furthermore, let’s look at a random sample of five out of the 142 countries in <a href="#tbl-model2-data-preview" class="quarto-xref">Table&nbsp;<span>5.4</span></a>. Again, note due to the random nature of the sampling, you will likely end up with a different subset of 5 rows.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>gapminder2007 <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-model2-data-preview" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-model2-data-preview-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.4: Random sample of 5 out of 142 countries
</figcaption>
<div aria-describedby="tbl-model2-data-preview-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">country</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">lifeExp</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">continent</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">gdpPercap</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Togo</td>
<td style="text-align: right;">58.4</td>
<td style="text-align: left;">Africa</td>
<td style="text-align: right;">883</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sao Tome and Principe</td>
<td style="text-align: right;">65.5</td>
<td style="text-align: left;">Africa</td>
<td style="text-align: right;">1598</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Congo, Dem. Rep.</td>
<td style="text-align: right;">46.5</td>
<td style="text-align: left;">Africa</td>
<td style="text-align: right;">278</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lesotho</td>
<td style="text-align: right;">42.6</td>
<td style="text-align: left;">Africa</td>
<td style="text-align: right;">1569</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bulgaria</td>
<td style="text-align: right;">73.0</td>
<td style="text-align: left;">Europe</td>
<td style="text-align: right;">10681</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Now that we’ve looked at the raw values in our <code>gapminder2007</code> data frame and got a sense of the data, let’s move on to computing summary statistics. Let’s once again apply the <code>skim()</code> function from the <code>skimr</code> package. Recall from our previous EDA that this function takes in a data frame, “skims” it, and returns commonly used summary statistics. Let’s take our <code>gapminder2007</code> data frame, <code>select()</code> only the outcome and explanatory variables <code>lifeExp</code> and <code>continent</code>, and pipe them into the <code>skim()</code> function:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>gapminder2007 <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(lifeExp, continent) <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">skim</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<pre><code>── Data Summary ────────────────────────
                           Values    
Name                       Piped data
Number of rows             142       
Number of columns          2         
_______________________              
Column type frequency:               
  factor                   1         
  numeric                  1         
________________________             
Group variables            None      

── Variable type: factor ───────────────────────────────────────────────────────────────────
  skim_variable n_missing complete_rate ordered n_unique top_counts                        
1 continent             0             1 FALSE          5 Afr: 52, Asi: 33, Eur: 30, Ame: 25

── Variable type: numeric ──────────────────────────────────────────────────────────────────
  skim_variable n_missing complete_rate mean   sd   p0  p25  p50  p75 p100 hist 
1 lifeExp               0             1 67.0 12.1 39.6 57.2 71.9 76.4 82.6 ▂▃▃▆▇</code></pre>
<p>The <code>skim()</code> output now reports summaries for categorical variables (<code>Variable type:factor</code>) separately from the numerical variables (<code>Variable type:numeric</code>). For the categorical variable <code>continent</code>, it reports:</p>
<ul>
<li><p><code>n_missing</code> and <code>complete_rate</code>, which are the number of missing and proportion of non-missing values, respectively.</p></li>
<li><p><code>n_unique</code>: The number of unique levels to this variable, corresponding to Africa, Asia, Americas, Europe, and Oceania. This refers to the how many countries are in the data for each continent.</p></li>
<li><p><code>top_counts</code>: In this case the top four counts: <code>Africa</code> has 52 countries, <code>Asia</code> has 33, <code>Europe</code> has 30, and <code>Americas</code> has 25. Not displayed is <code>Oceania</code> with 2 countries.</p></li>
</ul>
<p>Turning our attention to the summary statistics of the numerical variable <code>lifeExp</code>, we observe that the global median life expectancy in 2007 was 71.94. Thus, half of the world’s countries (71 countries) had a life expectancy less than 71.94. The mean life expectancy of 67.01 is lower however. Why is the mean life expectancy lower than the median?</p>
<p>We can answer this question by performing the last of the three common steps in an exploratory data analysis: creating data visualizations. Let’s visualize the distribution of our outcome variable <span class="math inline">\(y\)</span> = <code>lifeExp</code> in <a href="#fig-lifeExp2007hist" class="quarto-xref">Figure&nbsp;<span>5.8</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(gapminder2007, <span class="fu">aes</span>(<span class="at">x =</span> lifeExp)) <span class="sc">+</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Life expectancy"</span>, </span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of countries"</span>,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Histogram of distribution of worldwide life expectancies"</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-lifeExp2007hist" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lifeExp2007hist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-regression_files/figure-html/fig-lifeExp2007hist-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lifeExp2007hist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.8: Histogram of Life Expectancy in 2007
</figcaption>
</figure>
</div>
</div>
</div>
<p>We see that this data is <em>left-skewed</em>, also known as <em>negatively</em> skewed: there are a few countries with low life expectancy that are bringing down the mean life expectancy. However, the median is less sensitive to the effects of such outliers; hence, the median is greater than the mean in this case.</p>
<p>Remember, however, that we want to compare life expectancies both between continents and within continents. In other words, our visualizations need to incorporate some notion of the variable <code>continent</code>. We can do this easily with a faceted histogram. Recall from <a href="02-visualization.html#sec-facets" class="quarto-xref"><span>Section 2.6</span></a> that facets allow us to split a visualization by the different values of another variable. We display the resulting visualization in <a href="#fig-catxplot0b" class="quarto-xref">Figure&nbsp;<span>5.9</span></a> by adding a <code>facet_wrap(~ continent, nrow = 2)</code> layer.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(gapminder2007, <span class="fu">aes</span>(<span class="at">x =</span> lifeExp)) <span class="sc">+</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Life expectancy"</span>,</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of countries"</span>,</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Histogram of distribution of worldwide life expectancies"</span>) <span class="sc">+</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> continent, <span class="at">nrow =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-catxplot0b" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-catxplot0b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-regression_files/figure-html/fig-catxplot0b-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-catxplot0b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.9: Life expectancy in 2007
</figcaption>
</figure>
</div>
</div>
</div>
<p>Observe that unfortunately the distribution of African life expectancies is much lower than the other continents, while in Europe life expectancies tend to be higher and furthermore do not vary as much. On the other hand, both Asia and Africa have the most variation in life expectancies. There is the least variation in Oceania, but keep in mind that there are only two countries in Oceania: Australia and New Zealand.</p>
<p>Recall that an alternative method to visualize the distribution of a numerical variable split by a categorical variable is by using a side-by-side boxplot. We map the categorical variable <code>continent</code> to the <span class="math inline">\(x\)</span>-axis and the different life expectancies within each continent on the <span class="math inline">\(y\)</span>-axis in <a href="#fig-catxplot1" class="quarto-xref">Figure&nbsp;<span>5.10</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(gapminder2007, <span class="fu">aes</span>(<span class="at">x =</span> continent, <span class="at">y =</span> lifeExp)) <span class="sc">+</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Continent"</span>, </span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Life expectancy (years)"</span>,</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Life expectancy by continent"</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-catxplot1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-catxplot1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-regression_files/figure-html/fig-catxplot1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-catxplot1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.10: Life expectancy in 2007
</figcaption>
</figure>
</div>
</div>
</div>
<p>Some people prefer comparing the distributions of a numerical variable between different levels of a categorical variable using a boxplot instead of a faceted histogram. This is because we can make quick comparisons between the categorical variable’s levels with imaginary horizontal lines. For example, observe in <a href="#fig-catxplot1" class="quarto-xref">Figure&nbsp;<span>5.10</span></a> that we can quickly convince ourselves that Oceania has the highest median life expectancies by drawing an imaginary horizontal line at <span class="math inline">\(y\)</span> = 80. Furthermore, as we observed in the faceted histogram in <a href="#fig-catxplot0b" class="quarto-xref">Figure&nbsp;<span>5.9</span></a>, Africa and Asia have the largest variation in life expectancy as evidenced by their large interquartile ranges (the heights of the boxes).</p>
<p>It’s important to remember however that the solid lines in the middle of the boxes correspond to the medians (the middle value) rather than the mean (the average). So for example, if you look at Asia, the solid line denotes the median life expectancy of around 72 years. This tells us that half of all countries in Asia have a life expectancy below 72 years whereas half have a life expectancy above 72 years.</p>
<p>Let’s compute the median and mean life expectancy for each continent with a little more data wrangling and display the results in <a href="#tbl-catxplot0" class="quarto-xref">Table&nbsp;<span>5.5</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>lifeExp_by_continent <span class="ot">&lt;-</span> gapminder2007 <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(continent) <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">median =</span> <span class="fu">median</span>(lifeExp), <span class="at">mean =</span> <span class="fu">mean</span>(lifeExp))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-catxplot0" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-catxplot0-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.5: Life expectancy by continent
</figcaption>
<div aria-describedby="tbl-catxplot0-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">continent</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">median</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Africa</td>
<td style="text-align: right;">52.9</td>
<td style="text-align: right;">54.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">Americas</td>
<td style="text-align: right;">72.9</td>
<td style="text-align: right;">73.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Asia</td>
<td style="text-align: right;">72.4</td>
<td style="text-align: right;">70.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">Europe</td>
<td style="text-align: right;">78.6</td>
<td style="text-align: right;">77.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Oceania</td>
<td style="text-align: right;">80.7</td>
<td style="text-align: right;">80.7</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Observe the order of the second column <code>median</code> life expectancy: Africa is lowest, the Americas and Asia are next with similar medians, then Europe, then Oceania. This ordering corresponds to the ordering of the solid black lines inside the boxes in our side-by-side boxplot in <a href="#fig-catxplot1" class="quarto-xref">Figure&nbsp;<span>5.10</span></a>.</p>
<p>Let’s now turn our attention to the values in the third column <code>mean</code>. Using Africa’s mean life expectancy of 54.8 as a <em>baseline for comparison</em>, let’s start making relative comparisons to the life expectancies of the other four continents:</p>
<ol type="1">
<li><p>The mean life expectancy of the Americas is 73.6 - 54.8 = 18.8 years higher.</p></li>
<li><p>The mean life expectancy of Asia is 70.7 - 54.8 = 15.9 years higher.</p></li>
<li><p>The mean life expectancy of Europe is 77.6 - 54.8 = 22.8 years higher.</p></li>
<li><p>The mean life expectancy of Oceania is 80.7 - 54.8 = 25.9 years higher.</p></li>
</ol>
<p>Let’s put these values in <a href="#tbl-continent-mean-life-expectancies" class="quarto-xref">Table&nbsp;<span>5.6</span></a>, which we’ll revisit later on in this section.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-continent-mean-life-expectancies" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-continent-mean-life-expectancies-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.6: Mean life expectancy by continent and relative differences from mean for Africa
</figcaption>
<div aria-describedby="tbl-continent-mean-life-expectancies-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">continent</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Difference versus Africa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Africa</td>
<td style="text-align: right;">54.8</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Americas</td>
<td style="text-align: right;">73.6</td>
<td style="text-align: right;">18.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Asia</td>
<td style="text-align: right;">70.7</td>
<td style="text-align: right;">15.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Europe</td>
<td style="text-align: right;">77.6</td>
<td style="text-align: right;">22.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Oceania</td>
<td style="text-align: right;">80.7</td>
<td style="text-align: right;">25.9</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="emoji" data-emoji="dart">🎯</span> Learning Check 5.3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Conduct a new exploratory data analysis with the same explanatory variable <span class="math inline">\(x\)</span> being <code>continent</code> but with <code>gdpPercap</code> as the new outcome variable <span class="math inline">\(y\)</span>. Remember, this involves three things:</p>
<ol type="1">
<li>Most crucially: Looking at the raw data values.</li>
<li>Computing summary statistics, such as means, medians, and interquartile ranges.</li>
<li>Creating data visualizations.</li>
</ol>
<p>What can you say about the differences in GDP per capita between continents based on this exploration?</p>
</div>
</div>
</div>
</section>
<section id="sec-model2table" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="sec-model2table"><span class="header-section-number">5.2.2</span> Linear regression</h3>
<p>In <a href="#sec-model1table" class="quarto-xref">Subsection&nbsp;<span>5.1.2</span></a> we introduced <em>simple</em> linear regression, which involves modeling the relationship between a numerical outcome variable <span class="math inline">\(y\)</span> as a function of a numerical explanatory variable <span class="math inline">\(x\)</span>, in our life expectancy example, we now have a categorical explanatory variable <span class="math inline">\(x\)</span> <code>continent</code>. While we still can fit a regression model, given our categorical explanatory variable we no longer have a concept of a “best-fitting” line, but rather “differences relative to a baseline for comparison.”</p>
<p>Before we fit our regression model, let’s create a table similar to <a href="#tbl-catxplot0" class="quarto-xref">Table&nbsp;<span>5.5</span></a>, but</p>
<ol type="1">
<li><p>Report the mean life expectancy for each continent.</p></li>
<li><p>Report the difference in mean life expectancy <em>relative</em> to Africa’s mean life expectancy of 54.806 in the column “mean vs Africa”; this column is simply the “mean” column minus 54.806.</p></li>
</ol>
<p>Think back to your observations from the eyeball test of <a href="#fig-catxplot1" class="quarto-xref">Figure&nbsp;<span>5.10</span></a> at the end of the last subsection. The column “mean vs Africa” is the same idea of comparing a summary statistic to a baseline for comparison, in this case the countries of Africa, but using means instead of medians.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-continent-mean-life-expectancies-" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-continent-mean-life-expectancies--caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.7: Mean life expectancy by continent
</figcaption>
<div aria-describedby="tbl-continent-mean-life-expectancies--caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">continent</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean vs Africa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Africa</td>
<td style="text-align: right;">54.8</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Americas</td>
<td style="text-align: right;">73.6</td>
<td style="text-align: right;">18.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Asia</td>
<td style="text-align: right;">70.7</td>
<td style="text-align: right;">15.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Europe</td>
<td style="text-align: right;">77.6</td>
<td style="text-align: right;">22.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Oceania</td>
<td style="text-align: right;">80.7</td>
<td style="text-align: right;">25.9</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Now, let’s use the <code>summary()</code> function again to get the <em>regression table</em> for the <code>gapminder2007</code> analysis:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>lifeExp_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(lifeExp <span class="sc">~</span> continent, <span class="at">data =</span> gapminder2007)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lifeExp_model)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-catxplot4b" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-catxplot4b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.8: Linear regression table
</figcaption>
<div aria-describedby="tbl-catxplot4b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Std. Error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">54.8</td>
<td style="text-align: right;">1.02</td>
<td style="text-align: right;">53.45</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">continentAmericas</td>
<td style="text-align: right;">18.8</td>
<td style="text-align: right;">1.80</td>
<td style="text-align: right;">10.45</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">continentAsia</td>
<td style="text-align: right;">15.9</td>
<td style="text-align: right;">1.65</td>
<td style="text-align: right;">9.68</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">continentEurope</td>
<td style="text-align: right;">22.8</td>
<td style="text-align: right;">1.70</td>
<td style="text-align: right;">13.47</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">continentOceania</td>
<td style="text-align: right;">25.9</td>
<td style="text-align: right;">5.33</td>
<td style="text-align: right;">4.86</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Just as before, we’re only interested in the “Estimate” column, but unlike before, we now have 5 rows corresponding to 5 outputs in our table: an intercept like before, but also <code>continentAmericas</code>, <code>continentAsia</code>, <code>continentEurope</code>, and <code>continentOceania</code>. What are these values? First, we must describe the equation for fitted value <span class="math inline">\(\widehat{y}\)</span>, which is a little more complicated when the <span class="math inline">\(x\)</span> explanatory variable is categorical:</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{\text{life exp}} &amp;= b_0 + b_{\text{Amer}}\cdot\mathbb{1}_{\mbox{Amer}}(x) + b_{\text{Asia}}\cdot\mathbb{1}_{\mbox{Asia}}(x)
+ b_{\text{Euro}}\cdot\mathbb{1}_{\mbox{Euro}}(x) + b_{\text{Ocean}}\cdot\mathbb{1}_{\mbox{Ocean}}(x)\\
&amp;= 54.8 + 18.8\cdot\mathbb{1}_{\mbox{Amer}}(x) + 15.9\cdot\mathbb{1}_{\mbox{Asia}}(x)
+ 22.8\cdot\mathbb{1}_{\mbox{Euro}}(x) + 25.9\cdot\mathbb{1}_{\mbox{Ocean}}(x)
\end{aligned}
\]</span></p>
<p>Let’s break this down. First, <span class="math inline">\(\mathbb{1}_{A}(x)\)</span> is what’s known in mathematics as an “indicator function” that takes one of two possible values:</p>
<!-- $$ -->
<!-- \mathbb{1}_{A}(x) = \left\{ -->
<!-- \begin{array}{ll} -->
<!-- 1 & \text{if } x \text{ is in } A \\ -->
<!-- 0 & \text{otherwise} \end{array} -->
<!-- \right. -->
<!-- $$ -->
<p><span class="math display">\[
\mathbb{1}_{A}(x) =
\begin{cases}
  1 &amp; \text{if } x \in A \\
  0 &amp; \text{otherwise}
\end{cases}
\]</span></p>
<p>In a statistical modeling context this is also known as a “dummy variable”. In our case, let’s consider the first such indicator variable:</p>
<p><span class="math display">\[
\mathbb{1}_{\mbox{Amer}}(x) = \left\{
\begin{array}{ll}
1 &amp; \text{if } \text{country } x \text{ is in the Americas} \\
0 &amp; \text{otherwise}\end{array}
\right.
\]</span></p>
<p>Now let’s interpret the terms in the estimate column of the regression table. First <span class="math inline">\(b_0 =\)</span> <code>intercept = 54.8</code> corresponds to the mean life expectancy for countries in Africa, since for country <span class="math inline">\(x\)</span> in Africa we have the following equation:</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{\text{life exp}} &amp;= b_0 + b_{\text{Amer}}\cdot\mathbb{1}_{\mbox{Amer}}(x) + b_{\text{Asia}}\cdot\mathbb{1}_{\mbox{Asia}}(x)
+ b_{\text{Euro}}\cdot\mathbb{1}_{\mbox{Euro}}(x) + b_{\text{Ocean}}\cdot\mathbb{1}_{\mbox{Ocean}}(x)\\
&amp;= 54.8 + 18.8\cdot\mathbb{1}_{\mbox{Amer}}(x) + 15.9\cdot\mathbb{1}_{\mbox{Asia}}(x)
+ 22.8\cdot\mathbb{1}_{\mbox{Euro}}(x) + 25.9\cdot\mathbb{1}_{\mbox{Ocean}}(x)\\
&amp;= 54.8 + 18.8\cdot 0 + 15.9\cdot 0 + 22.8\cdot 0 + 25.9\cdot 0\\
&amp;= 54.8
\end{aligned}
\]</span></p>
<p>Meaning, all four of the indicator variables are equal to 0. Recall we stated earlier that we would treat Africa as the baseline for comparison group. Furthermore, this value corresponds to the group mean life expectancy for all African countries in <a href="#tbl-continent-mean-life-expectancies" class="quarto-xref">Table&nbsp;<span>5.6</span></a>.</p>
<p>Next, <span class="math inline">\(b_{\text{Amer}}\)</span> = <code>continentAmericas = 18.8</code> is the difference in mean life expectancy of countries in the Americas relative to Africa, or in other words, on average countries in the Americas had life expectancy 18.8 years greater. The fitted value yielded by this equation is:</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{\text{life exp}} &amp;= b_0 + b_{\text{Amer}}\cdot\mathbb{1}_{\mbox{Amer}}(x) + b_{\text{Asia}}\cdot\mathbb{1}_{\mbox{Asia}}(x)
+ b_{\text{Euro}}\cdot\mathbb{1}_{\mbox{Euro}}(x) + b_{\text{Ocean}}\cdot\mathbb{1}_{\mbox{Ocean}}(x)\\
&amp;= 54.8 + 18.8\cdot\mathbb{1}_{\mbox{Amer}}(x) + 15.9\cdot\mathbb{1}_{\mbox{Asia}}(x)
+ 22.8\cdot\mathbb{1}_{\mbox{Euro}}(x) + 25.9\cdot\mathbb{1}_{\mbox{Ocean}}(x)\\
&amp;= 54.8 + 18.8\cdot 1 + 15.9\cdot 0 + 22.8\cdot 0 + 25.9\cdot 0\\
&amp;= 54.8 + 18.8\\
&amp;= 73.6
\end{aligned}
\]</span></p>
<p>i.e.&nbsp;in this case, only the indicator function <span class="math inline">\(\mathbb{1}_{\mbox{Amer}}(x)\)</span> is equal to 1, but all others are 0. Recall that 73.6 corresponds to the group mean life expectancy for all countries in the Americas in <a href="#tbl-continent-mean-life-expectancies" class="quarto-xref">Table&nbsp;<span>5.6</span></a>.</p>
<p>Similarly, <span class="math inline">\(b_{\text{Asia}}\)</span> = <code>continentAsia = 15.9</code> is the difference in mean life expectancy of Asian countries relative to Africa countries, or in other words, on average countries in the Asia had life expectancy 15.9 years greater than Africa. The fitted value yielded by this equation is:</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{\text{life exp}} &amp;= b_0 + b_{\text{Amer}}\cdot\mathbb{1}_{\mbox{Amer}}(x) + b_{\text{Asia}}\cdot\mathbb{1}_{\mbox{Asia}}(x)
+ b_{\text{Euro}}\cdot\mathbb{1}_{\mbox{Euro}}(x) + b_{\text{Ocean}}\cdot\mathbb{1}_{\mbox{Ocean}}(x)\\
&amp;= 54.8 + 18.8\cdot\mathbb{1}_{\mbox{Amer}}(x) + 15.9\cdot\mathbb{1}_{\mbox{Asia}}(x)
+ 22.8\cdot\mathbb{1}_{\mbox{Euro}}(x) + 25.9\cdot\mathbb{1}_{\mbox{Ocean}}(x)\\
&amp;= 54.8 + 18.8\cdot 0 + 15.9\cdot 1 + 22.8\cdot 0 + 25.9\cdot 0\\
&amp;= 54.8 + 15.9\\
&amp;= 70.7
\end{aligned}
\]</span></p>
<p>Meaning, in this case, only the indicator function <span class="math inline">\(\mathbb{1}_{\mbox{Asia}}(x)\)</span> is equal to 1, but all others are 0. Recall that 70.7 corresponds to the group mean life expectancy for all countries in Asia in <a href="#tbl-continent-mean-life-expectancies" class="quarto-xref">Table&nbsp;<span>5.6</span></a>. The same logic applies to <span class="math inline">\(b_{\text{Euro}} = 22.8\)</span> and <span class="math inline">\(b_{\text{Ocean}} = 25.9\)</span>; they correspond to the “offset” in mean life expectancy for countries in Europe and Oceania, relative to the mean life expectancy of the baseline group for comparison of African countries.</p>
<p>Let’s generalize this idea a bit. If we fit a linear regression model using a categorical explanatory variable <span class="math inline">\(x\)</span> that has <span class="math inline">\(k\)</span> levels, a regression model will return an intercept and <span class="math inline">\(k - 1\)</span> “slope” coefficients. When <span class="math inline">\(x\)</span> is a numerical explanatory variable the interpretation is of a “slope” coefficient, but when <span class="math inline">\(x\)</span> is categorical the meaning is a little trickier. They are <em>offsets</em> relative to the baseline.</p>
<p>In our case, since there are <span class="math inline">\(k = 5\)</span> continents, the regression model returns an intercept corresponding to the baseline for comparison Africa and <span class="math inline">\(k - 1 = 4\)</span> slope coefficients corresponding to the Americas, Asia, Europe, and Oceania. Africa was chosen as the baseline by R for no other reason than it is first alphabetically of the 5 continents. You can manually specify which continent to use as baseline instead of the default choice of whichever comes first alphabetically, but we leave that to a more advanced course. (The <code>forcats</code> package is particularly nice for doing this and we encourage you to explore using it.)</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="emoji" data-emoji="dart">🎯</span> Learning Check 5.4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Fit a new linear regression using <code>lm(gdpPercap ~ continent, data = gapminder2007)</code> where <code>gdpPercap</code> is the new outcome variable <span class="math inline">\(y\)</span>. Get information about the “best-fitting” line from the regression table by applying the <code>summary()</code> function. How do the regression results match up with the results from your exploratory data analysis above?</p>
</div>
</div>
</div>
</section>
<section id="sec-model2points" class="level3" data-number="5.2.3">
<h3 data-number="5.2.3" class="anchored" data-anchor-id="sec-model2points"><span class="header-section-number">5.2.3</span> Observed/fitted values and residuals</h3>
<p>Recall in <a href="#sec-model1points" class="quarto-xref">Subsection&nbsp;<span>5.1.3</span></a> we defined the following three concepts:</p>
<ol type="1">
<li><p>Observed values <span class="math inline">\(y\)</span>, or the observed value of the outcome variable</p></li>
<li><p>Fitted values <span class="math inline">\(\widehat{y}\)</span>, or the value on the regression line for a given <span class="math inline">\(x\)</span> value</p></li>
<li><p>Residuals <span class="math inline">\(y - \widehat{y}\)</span>, or the error between the observed value and the fitted value</p></li>
</ol>
<p>Let’s use similar code (from <a href="#sec-model1points" class="quarto-xref">Subsection&nbsp;<span>5.1.3</span></a>) to obtain these values for the <code>lifeExp_model</code> fit to the <code>gapminder2007</code> dataset:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>lifeExp_model_data <span class="ot">&lt;-</span> gapminder2007 <span class="sc">%&gt;%</span> </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(country, lifeExp, continent) <span class="sc">%&gt;%</span> </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">lifeExp_hat =</span> <span class="fu">fitted</span>(lifeExp_model),</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">residual =</span> <span class="fu">residuals</span>(lifeExp_model)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-lifeExp-reg-points" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-lifeExp-reg-points-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.9: Regression points (First 10 out of 142 countries)
</figcaption>
<div aria-describedby="tbl-lifeExp-reg-points-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">country</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">lifeExp</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">continent</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">lifeExp_hat</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">residual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Afghanistan</td>
<td style="text-align: right;">43.8</td>
<td style="text-align: left;">Asia</td>
<td style="text-align: right;">70.7</td>
<td style="text-align: right;">-26.900</td>
</tr>
<tr class="even">
<td style="text-align: left;">Albania</td>
<td style="text-align: right;">76.4</td>
<td style="text-align: left;">Europe</td>
<td style="text-align: right;">77.6</td>
<td style="text-align: right;">-1.226</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Algeria</td>
<td style="text-align: right;">72.3</td>
<td style="text-align: left;">Africa</td>
<td style="text-align: right;">54.8</td>
<td style="text-align: right;">17.495</td>
</tr>
<tr class="even">
<td style="text-align: left;">Angola</td>
<td style="text-align: right;">42.7</td>
<td style="text-align: left;">Africa</td>
<td style="text-align: right;">54.8</td>
<td style="text-align: right;">-12.075</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Argentina</td>
<td style="text-align: right;">75.3</td>
<td style="text-align: left;">Americas</td>
<td style="text-align: right;">73.6</td>
<td style="text-align: right;">1.712</td>
</tr>
<tr class="even">
<td style="text-align: left;">Australia</td>
<td style="text-align: right;">81.2</td>
<td style="text-align: left;">Oceania</td>
<td style="text-align: right;">80.7</td>
<td style="text-align: right;">0.516</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Austria</td>
<td style="text-align: right;">79.8</td>
<td style="text-align: left;">Europe</td>
<td style="text-align: right;">77.6</td>
<td style="text-align: right;">2.180</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bahrain</td>
<td style="text-align: right;">75.6</td>
<td style="text-align: left;">Asia</td>
<td style="text-align: right;">70.7</td>
<td style="text-align: right;">4.907</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bangladesh</td>
<td style="text-align: right;">64.1</td>
<td style="text-align: left;">Asia</td>
<td style="text-align: right;">70.7</td>
<td style="text-align: right;">-6.666</td>
</tr>
<tr class="even">
<td style="text-align: left;">Belgium</td>
<td style="text-align: right;">79.4</td>
<td style="text-align: left;">Europe</td>
<td style="text-align: right;">77.6</td>
<td style="text-align: right;">1.792</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Observe in <a href="#tbl-lifeExp-reg-points" class="quarto-xref">Table&nbsp;<span>5.9</span></a> that <code>lifeExp_hat</code> contains the fitted values <span class="math inline">\(\hat{y} = \widehat{lifeExp}\)</span>. If you look closely, there are only 5 possible values for <code>lifeExp_hat</code>. These correspond to the five mean life expectancies for the 5 continents that we displayed in <a href="#tbl-continent-mean-life-expectancies" class="quarto-xref">Table&nbsp;<span>5.6</span></a> and computed using the “Estimate” column of the regression results in @tbl-catxplot4b.</p>
<p>The <code>residual</code> column is simply <span class="math inline">\(y - \widehat{y}\)</span> = <code>lifeexp - lifeexp_hat</code>. These values can be interpreted as that particular country’s deviation from the mean life expectancy of the respective continent’s mean. For example, the first row of Table @ref(tab:lifeExp-reg-points) corresponds to Afghanistan, and the residual of <span class="math inline">\(y - \widehat{y} = 43.8 - 70.7 = -26.9\)</span> is telling us that Afghanistan’s life expectancy is a whopping 26.9 years lower than the mean life expectancy of all Asian countries. This can in part be explained by the many years of war that country has suffered.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="emoji" data-emoji="dart">🎯</span> Learning Check 5.5
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Using either the sorting functionality of RStudio’s spreadsheet viewer or using the data wrangling tools you learned in <a href="03-wrangling.html" class="quarto-xref"><span>Chapter 3</span></a>, identify the five countries with the five smallest (most negative) residuals? What do these negative residuals say about their life expectancy relative to their continents?</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="emoji" data-emoji="dart">🎯</span> Learning Check 5.6
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Repeat this process, but identify the five countries with the five largest (most positive) residuals. What do these positive residuals say about their life expectancy relative to their continents?</p>
</div>
</div>
</div>
</section>
</section>
<section id="related-topics" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="related-topics"><span class="header-section-number">5.3</span> Related topics</h2>
<section id="sec-correlationcoefficient" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="sec-correlationcoefficient"><span class="header-section-number">5.3.1</span> Correlation coefficient</h3>
<p>Let’s re-plot <a href="#fig-correlation1" class="quarto-xref">Figure&nbsp;<span>5.1</span></a>, but now consider a broader range of correlation coefficient values in <a href="#fig-correlation2" class="quarto-xref">Figure&nbsp;<span>5.11</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-correlation2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-correlation2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-regression_files/figure-html/fig-correlation2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-correlation2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.11: Different Correlation Coefficients
</figcaption>
</figure>
</div>
</div>
</div>
<p>As we suggested in <a href="#sec-model1EDA" class="quarto-xref">Subsection&nbsp;<span>5.1.1</span></a>, interpreting coefficients that are not close to the extreme values of -1 and 1 can be subjective. To help develop your sense of correlation coefficients, we suggest you play the following 80’s-style video game called “Guess the correlation” at <a href="http://guessthecorrelation.com/" class="uri">http://guessthecorrelation.com/</a>.</p>
</section>
<section id="sec-correlation-is-not-causation" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="sec-correlation-is-not-causation"><span class="header-section-number">5.3.2</span> Correlation is not necessarily causation</h3>
<p>You’ll note throughout this chapter we’ve been very cautious in making statements of the “associated effect” of explanatory variables on the outcome variables, for example our statement from <a href="#sec-model1table" class="quarto-xref">Subsection&nbsp;<span>5.1.2</span></a> that “for every increase of 1 unit in <code>bty_avg</code>, there is an <em>associated</em> increase of, <em>on average</em>, 18.802 units of <code>score</code>.” We stay this because we are careful not to make <em>causal</em> statements. So while beauty score <code>bty_avg</code> is positively correlated with teaching <code>score</code>, does it directly cause effects on teaching score.</p>
<p>For example, let’s say an instructor has their <code>bty_avg</code> reevaluated, but only after taking steps to try to boost their beauty score. Does this mean that they will suddenly be a better instructor? Or will they suddenly get higher teaching scores? Maybe?</p>
<p>Here is another example, a not-so-great medical doctor goes through their medical records and finds that patients who slept with their shoes on tended to wake up more with headaches. So this doctor declares “Sleeping with shoes on cause headaches!”</p>
<div id="fig-sleep-shoes-on" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sleep-shoes-on-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/flowcharts/flowchart.010-cropped.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sleep-shoes-on-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.12: Does sleeping with shoes on cause headaches?
</figcaption>
</figure>
</div>
<p>However as some of you might have guessed, if someone is sleeping with their shoes on it’s probably because they are intoxicated. Furthermore, drinking more tends to cause more hangovers, and hence more headaches.</p>
<p>In this instance, alcohol is what’s known as a <em>confounding/lurking</em> variable. It “lurks” behind the scenes, confounding or making less apparent, the causal effect (if any) of “sleeping with shoes on” with waking up with a headache. We can summarize this notion in <a href="#fig-moderndive-figure-causal-graph" class="quarto-xref">Figure&nbsp;<span>5.13</span></a> with a <em>causal graph</em> where:</p>
<ul>
<li>Y: Is an <em>outcome</em> variable, here “waking up with a headache.”</li>
<li>X: Is a <em>treatment</em> variable whose causal effect we are interested in, here “sleeping with shoes on.”</li>
</ul>
<div id="fig-moderndive-figure-causal-graph" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-moderndive-figure-causal-graph-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/flowcharts/flowchart.009-cropped.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-moderndive-figure-causal-graph-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.13: Causal graph
</figcaption>
</figure>
</div>
<p>So for example, many such studies use regression modeling where the outcome variable is set to Y and the explanatory/predictor variable is X, much as you’ve started learning how to do in this chapter. However, <a href="#fig-moderndive-figure-causal-graph" class="quarto-xref">Figure&nbsp;<span>5.13</span></a> also includes a third variable with arrows pointing at both X and Y.</p>
<ul>
<li>Z: Is a <em>confounding</em> variable that affects both X &amp; Y, thus “confounding” their relationship.</li>
</ul>
<p>So as we said, alcohol will both cause people to be more likely to sleep with their shoes on as well as more likely to wake up with a headache. Thus when evaluating what causes one to wake up with a headache, its hard to tease out the effect of sleeping with shoes on versus just the alcohol. Thus our model needs to also use Z as an explanatory/predictor variable as well, in other words our doctor needs to take into account who had been drinking the night before. We’ll start covering multiple regression models that allows us to incorporate more than one variable in the next chapter.</p>
<p>Establishing causation is a tricky problem and frequently takes either carefully designed experiments or methods to control for the effects of potential confounding variables. Both these approaches attempt either to remove all confounding variables or take them into account as best they can, and only focus on the behavior of an outcome variable in the presence of the levels of the other variable(s). Be careful as you read studies to make sure that the writers aren’t falling into this fallacy of correlation implying causation. If you spot one, you may want to send them a link to <a href="http://www.tylervigen.com/spurious-correlations">Spurious Correlations</a>.</p>
</section>
<section id="sec-leastsquares" class="level3" data-number="5.3.3">
<h3 data-number="5.3.3" class="anchored" data-anchor-id="sec-leastsquares"><span class="header-section-number">5.3.3</span> Best-fitting line</h3>
<p>Regression lines are also known as “best-fitting” lines. But what do we mean by “best”? Let’s unpack the criteria that is used in regression to determine “best.” Recall <a href="#fig-numxplot4" class="quarto-xref">Figure&nbsp;<span>5.6</span></a>, where for an instructor with a beauty score of <span class="math inline">\(x = 7.333\)</span> we mark the <em>observed value</em> <span class="math inline">\(y\)</span> with a circle, the <em>fitted value</em> <span class="math inline">\(\widehat{y}\)</span> with a square, and the <em>residual</em> <span class="math inline">\(y - \widehat{y}\)</span> with an arrow.</p>
<p>We re-display <a href="#fig-numxplot4" class="quarto-xref">Figure&nbsp;<span>5.6</span></a> in the top-left plot of <a href="#fig-best-fitting-line" class="quarto-xref">Figure&nbsp;<span>5.14</span></a>. Furthermore, let’s repeat this for three more arbitrarily chosen course’s instructors:</p>
<ol type="1">
<li><p>A course whose instructor had a “beauty” score <span class="math inline">\(x\)</span> = 2.333 and teaching score <span class="math inline">\(y\)</span> = 2.7. The residual in this case is <span class="math inline">\(2.7 - 4.036 = -1.336\)</span>, which we mark with a new blue arrow in the top-right plot.</p></li>
<li><p>A course whose instructor had a “beauty” score <span class="math inline">\(x = 3.667\)</span> and teaching score <span class="math inline">\(y = 4.4\)</span>. The residual in this case is <span class="math inline">\(4.4 - 4.125 = 0.2753\)</span>, which we mark with a new blue arrow in the bottom-left plot.</p></li>
<li><p>A course whose instructor had a “beauty” score <span class="math inline">\(x = 6\)</span> and teaching score <span class="math inline">\(y = 3.8\)</span>. The residual in this case is <span class="math inline">\(3.8 - 4.28 = -0.4802\)</span>, which we mark with a new blue arrow in the bottom-right plot.</p></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-best-fitting-line" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-best-fitting-line-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="05-regression_files/figure-html/fig-best-fitting-line-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-best-fitting-line-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.14: Example of observed value, fitted value, and residual
</figcaption>
</figure>
</div>
</div>
</div>
<p>Now say we repeated this process of computing residuals for all 463 courses’ instructors, then we squared all the residuals, and then we summed them. We call this quantity the <em>sum of squared residuals</em> and it is a measure of the <em>lack of fit</em> of a model. Larger values of the sum of squared residuals indicate a bigger lack of fit. This corresponds to a worse fitting model.</p>
<p>If the regression line fits all the points perfectly, then the sum of squared residuals is 0. This is because if the regression line fits all the points perfectly, then the fitted value <span class="math inline">\(\widehat{y}\)</span> equals the observed value <span class="math inline">\(y\)</span> in all cases, and hence the residual <span class="math inline">\(y-\widehat{y}\)</span> = 0 in all cases, and the sum of even a large number of 0’s is still 0.</p>
<p>Furthermore, of all possible lines we can draw through the cloud of 463 points, the regression line minimizes this value. In other words, the regression and its corresponding fitted values <span class="math inline">\(\widehat{y}\)</span> minimizes the sum of the squared residuals:</p>
<p><span class="math display">\[
\sum_{i=1}^{n}(y_i - \widehat{y}_i)^2
\]</span></p>
<p>Let’s use our data wrangling tools from <a href="03-wrangling.html" class="quarto-xref"><span>Chapter 3</span></a> to compute the sum of squared residuals exactly:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit regression model:</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>score_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(score <span class="sc">~</span> bty_avg, <span class="at">data =</span> evals_ch5)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Get regression points:</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>score_model_data <span class="ot">&lt;-</span> evals_ch5 <span class="sc">%&gt;%</span> </span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(score, bty_avg) <span class="sc">%&gt;%</span> </span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">score_hat =</span> <span class="fu">fitted</span>(score_model),</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">residual =</span> <span class="fu">residuals</span>(score_model)</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span> </span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rownames_to_column</span>(<span class="st">"ID"</span>)</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute sum of squared residuals</span></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>score_model_data <span class="sc">%&gt;%</span></span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">squared_residuals =</span> residual<span class="sc">^</span><span class="dv">2</span>) <span class="sc">%&gt;%</span></span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">sum_of_squared_residuals =</span> <span class="fu">sum</span>(squared_residuals))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  sum_of_squared_residuals
                     &lt;dbl&gt;
1                     132.</code></pre>
</div>
</div>
<p>Any other straight line drawn in the figure would yield a sum of squared residuals greater than 132. This is a mathematically guaranteed fact that you can prove using calculus and linear algebra. That’s why alternative names for the linear regression line are the <em>best-fitting line</em> as well as the <em>least-squares line</em>. Why do we square the residuals (i.e.&nbsp;the arrow lengths)? We do this so that both positive and negative deviations of the same amount are treated equally.</p>
<!-- Can't seem to get this learning check to work with rendering to pdf. Issue is with figure in the middle of the callout box -->
<!-- :::{.callout-tip icon=false collapse=true} -->
<!-- ## :dart: Learning Check 5.7 -->
<!-- Note in the following plot there are 3 points marked with dots along with: -->
<!-- * The "best" fitting solid regression line in blue -->
<!-- * An arbitrarily chosen dotted red line  -->
<!-- * Another arbitrarily chosen dashed green line -->
<!-- ```{r} -->
<!-- #| label: fig-three-lines -->
<!-- #| fig-cap: "Regression line and two others" -->
<!-- #| echo: false -->
<!-- example <- tibble( -->
<!--   x = c(0, 0.5, 1), -->
<!--   y = c(2, 1, 3) -->
<!-- ) -->
<!-- ggplot(example, aes(x = x, y = y)) + -->
<!--   geom_smooth(method = "lm", se = FALSE, fullrange = TRUE) + -->
<!--   geom_hline(yintercept = 2.5, col = "red", linetype = "dotted", size = 1) + -->
<!--   geom_abline(intercept = 2, slope = -1, col = "forestgreen",  -->
<!--               linetype = "dashed", size = 1) + -->
<!--   geom_point(size = 4) -->
<!-- ``` -->
<!-- Compute the sum of squared residuals by hand for each line and show that of these three lines, the regression line in blue has the smallest value. -->
<!-- ::: -->
</section>
</section>
<section id="sec-basic-reg-conclusion" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="sec-basic-reg-conclusion"><span class="header-section-number">5.4</span> Conclusion</h2>
<section id="sec-additional-resources-basic-regression" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="sec-additional-resources-basic-regression"><span class="header-section-number">5.4.1</span> Additional resources</h3>
<p>As we suggested in <a href="#sec-model1EDA" class="quarto-xref">Subsection&nbsp;<span>5.1.1</span></a>, interpreting coefficients that are not close to the extreme values of -1, 0, and 1 can be somewhat subjective. To help develop your sense of correlation coefficients, we suggest you play the following 80’s-style video game called “Guess the correlation” at <a href="http://guessthecorrelation.com/" class="uri">http://guessthecorrelation.com/</a>.</p>
</section>
<section id="whats-to-come" class="level3" data-number="5.4.2">
<h3 data-number="5.4.2" class="anchored" data-anchor-id="whats-to-come"><span class="header-section-number">5.4.2</span> What’s to come?</h3>
<p>In this chapter, you’ve studied the term <em>basic regression</em>, where you fit models that only have one explanatory variable. In <a href="06-multiple-regression.html" class="quarto-xref"><span>Chapter 6</span></a>, we’ll study <em>multiple regression</em>, where our regression models can now have more than one explanatory variable! In particular, we’ll consider two scenarios: regression models with one numerical and one categorical explanatory variable and regression models with two numerical explanatory variables. This will allow you to construct more sophisticated and more powerful models, all in the hopes of better explaining your outcome variable <span class="math inline">\(y\)</span>.</p>
</section>
</section>
<section id="sec-ex05" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="sec-ex05"><span class="header-section-number">5.5</span> Exercises</h2>
<section id="sec-ex05-conceptual" class="level3" data-number="5.5.1">
<h3 data-number="5.5.1" class="anchored" data-anchor-id="sec-ex05-conceptual"><span class="header-section-number">5.5.1</span> Conceptual</h3>
<div id="exr-ch05-c01" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.1</strong></span> Match the following graph with the most appropriate correlation coefficient.</p>
<p><img src="images/cor_-0.7.png" style="height:1.5in"></p>
<ol type="a">
<li>-1</li>
<li>-0.9</li>
<li>-0.7</li>
<li>-0.4</li>
<li>None of the above, it is a positive association</li>
</ol>
</div>
<div id="exr-ch05-c02" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.2</strong></span> What is the most appropriate correlation between an hourly employees paycheck and the number of hours worked?</p>
<ol type="a">
<li>Exactly -1</li>
<li>Between -1 and 0</li>
<li>About 0</li>
<li>Between 0 and 1</li>
<li>Exactly 1</li>
</ol>
</div>
<div id="exr-ch05-c03" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.3</strong></span> What is the most appropriate correlation between the distance up a mountain and temperature?</p>
<ol type="a">
<li>Exactly -1</li>
<li>Between -1 and 0</li>
<li>About 0</li>
<li>Between 0 and 1</li>
<li>Exactly 1</li>
</ol>
</div>
<div id="exr-ch05-c04" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.4</strong></span> Select all that apply to complete the following statement: The variable x is also called the ____</p>
<ol type="a">
<li>explanatory variable</li>
<li>predictor variable</li>
<li>outcome variable</li>
<li>independent variable</li>
<li>dependent variable</li>
<li>covariate</li>
</ol>
</div>
<div id="exr-ch05-c05" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.5</strong></span> Select all that apply to complete the following statement: The variable y is also called the ____</p>
<ol type="a">
<li>explanatory variable</li>
<li>predictor variable</li>
<li>outcome variable</li>
<li>independent variable</li>
<li>dependent variable</li>
<li>covariate</li>
</ol>
</div>
<div id="exr-ch05-c06" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.6</strong></span> Consider the regression line <span class="math inline">\(\hat{y}=5.25+3.86x\)</span>. Which of the following does <span class="math inline">\(5.25\)</span> refer to? Select all that apply.</p>
<ol type="a">
<li>slope coefficient</li>
<li>the increase in <span class="math inline">\(\hat{y}\)</span> for every increase of 1 in <span class="math inline">\(x\)</span></li>
<li><span class="math inline">\(b_0\)</span></li>
<li><span class="math inline">\(b_1\)</span></li>
<li>the value of <span class="math inline">\(\hat{y}\)</span> when <span class="math inline">\(x=0\)</span></li>
<li>intercept</li>
</ol>
</div>
<div id="exr-ch05-c07" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.7</strong></span> Consider the regression line <span class="math inline">\(\hat{y}=5.25+3.86x\)</span>. Which of the following is the correct interpretation of 3.86?</p>
<ol type="a">
<li>For every increase of 1 unit in y, there is an associated increase of 3.86 units of x.</li>
<li>For every increase of 1 unit in x, there is an associated increase of 3.86 units of y.</li>
<li>For every increase of 1 unit in y, there is an associated increase of, on average, 3.86 units of x.</li>
<li>For every increase of 1 unit in x, there is an associated increase of, on average, 3.86 units of y.</li>
<li>For every increase of 1 unit in y, there is a causal increase of, on average, 3.86 units of x.</li>
<li>For every increase of 1 unit in x, there is a causal increase of, on average, 3.86 units of y.</li>
</ol>
</div>
<div id="exr-ch05-c08" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.8</strong></span> The residual is the difference between the observed value and the predicted value. This can be thought of as the error in prediction from the regression line.</p>
<ol type="a">
<li>TRUE</li>
<li>FALSE</li>
</ol>
</div>
<div id="exr-ch05-c09" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.9</strong></span> If a linear regression model <span class="math inline">\(y ~ x\)</span> is fitted where <span class="math inline">\(x\)</span> is a categorical variable, then <span class="math inline">\(b_1\)</span> is the mean of the baseline.</p>
<ol type="a">
<li>TRUE</li>
<li>FALSE</li>
</ol>
</div>
<div id="exr-ch05-c10" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.10</strong></span> The regression line minimizes the following equation <span class="math inline">\(\sum_{i=0}^{n}(y_i-\hat{y}_i)\)</span></p>
<ol type="a">
<li>TRUE</li>
<li>FALSE</li>
</ol>
</div>
<div id="exr-ch05-c11" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.11</strong></span> An ice cream company employee explores a dataset with information on shark attacks and ice cream sales, and notices a positive correlation between these two variables. The employee concludes that an increase in shark attacks will help them sell more ice cream. Is this conclusion correct?</p>
<ol type="a">
<li>Yes, the positive correlation shows that an increase in shark attacks causes ice cream sales to improve.</li>
<li>Yes, the positive correlation shows that an increase in ice cream sales causes shark attacks to increase.</li>
<li>No, the positive correlation shows that an increase in ice cream sales causes shark attacks to increase.</li>
<li>No, the positive correlation does not necessarily imply causation.</li>
</ol>
</div>
</section>
<section id="sec-ex05-application" class="level3" data-number="5.5.2">
<h3 data-number="5.5.2" class="anchored" data-anchor-id="sec-ex05-application"><span class="header-section-number">5.5.2</span> Application</h3>
<p>The <code>Auto</code> and <code>Bikeshare</code> datasets are in the <code>ISLR2</code> package.</p>
<div id="exr-ch05-app1" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.12</strong></span> Using the <code>Auto</code> dataset…</p>
<ol type="a">
<li>Conduct an exploratory data analysis. That is, use the <code>skim</code> function to describe the number of variables, observations, any missingness issues, and any potential problematic features.</li>
<li>Calculate the correlation between <code>mpg</code> and <code>horsepower</code>.</li>
<li>Plot the relationship of <code>mpg</code> by <code>horsepower</code>. Add the line of best fit to the scatterplot.</li>
<li>Fit a linear regression model to predict <code>mpg</code> based on <code>horsepower</code>. What is the equation of the line?</li>
<li>Interpret the intercept and slope in the context of the problem.</li>
<li>What is the expected <code>mpg</code> of a car with 150 `horsepower?</li>
</ol>
</div>
<div id="exr-ch05-app2" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.13</strong></span> Using the <code>Bikeshare</code> dataset, fit a simple linear regression model to predict the number of bikers using the temperature. Note: temperature is reported as a normalized unit in Celsius.</p>
<ol type="a">
<li>What is the correlation between <code>bikers</code> and <code>temp</code>.</li>
<li>Plot the relationship and line of best fit.</li>
<li>What is the equation of the line of best fit?</li>
<li>Interpret the intercept and slope in the context of the problem.</li>
<li>If the normalized temperature is 0.5, what is the predicted number of bikers?</li>
</ol>
</div>
<div id="exr-ch05-app3" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.14</strong></span> Using the <code>Bikeshare</code> dataset, fit a linear regression model to determine if the season can predict the number of bikers.</p>
<p>Hint: type <code>?Bikeshare</code> to view the help documentation and see the data type of <code>season</code>.</p>
<ol type="a">
<li>What is the model equation?</li>
<li>Interpret the intercept in the context of the problem.</li>
<li>Which season, on average, had the highest average number of bikers?</li>
<li>Which observation(s) did the model predict the worst?</li>
</ol>
</div>
</section>
<section id="sec-ex05-advanced" class="level3" data-number="5.5.3">
<h3 data-number="5.5.3" class="anchored" data-anchor-id="sec-ex05-advanced"><span class="header-section-number">5.5.3</span> Advanced</h3>
<div id="exr-ch05-adv1" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5.15</strong></span> The <code>summary</code> function and the <code>lm</code> function contain many values relevant to our analysis, including residuals and fitted values stored in the <code>lm</code> function and residuals, coefficients, R-squared and adjusted R-squared values all stored in the <code>summary</code> function.</p>
<p>Sometimes, it can be useful to extract these values directly from the result of the functions. These values can be accessed using the $ operator that we learned about in <a href="01-getting-started.html" class="quarto-xref"><span>Chapter 1</span></a>.</p>
<p>Using the model from <a href="#exr-ch05-app1" class="quarto-xref">Exercise&nbsp;<span>5.12</span></a>…</p>
<ol type="a">
<li>extract the <code>coefficients</code> directly from the model</li>
<li>extract the <code>r.squared</code> from the summary. This represents the proportion of variance in the dependent variable that can be explained by the independent variables. You will learn about this in detail in higher level regression courses.</li>
</ol>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-R-skimr" class="csl-entry" role="listitem">
Waring, Elin, Michael Quinn, Amelia McNamara, Eduardo Arino de la Rubia, Hao Zhu, and Shannon Ellis. 2022. <em>Skimr: Compact and Flexible Summaries of Data</em>. <a href="https://CRAN.R-project.org/package=skimr">https://CRAN.R-project.org/package=skimr</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/nustat\.github\.io\/intro-stat-data-sci\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./04-tidy.html" class="pagination-link" aria-label="Data Importing &amp; &quot;Tidy Data&quot;">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Importing &amp; “Tidy Data”</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./06-multiple-regression.html" class="pagination-link" aria-label="Multiple Regression">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Multiple Regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/NUstat/intro-stat-data-sci/edit/main/05-regression.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/NUstat/intro-stat-data-sci/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>