<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Introduction to Statistics and Data Science - 7&nbsp; Randomization and Causality</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./08-populations.html" rel="next">
<link href="./06-multiple-regression.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Randomization and Causality</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./" class="sidebar-logo-link">
      <img src="./images/logos/StatisticsDataScience-LogoSemi-VertPurple.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Statistics and Data Science</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/NUstat/intro-stat-data-sci" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
    <a href="./Introduction-to-Statistics-and-Data-Science.pdf" title="Download PDF" class="sidebar-tool px-1"><i class="bi bi-file-pdf"></i></a>
    <a href="" title="Share" id="sidebar-tool-dropdown-0" class="sidebar-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-share"></i></a>
    <ul class="dropdown-menu" aria-labelledby="sidebar-tool-dropdown-0">
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
            <i class="bi bi-bi-twitter pe-1"></i>
          Twitter
          </a>
        </li>
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
            <i class="bi bi-bi-facebook pe-1"></i>
          Facebook
          </a>
        </li>
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
            <i class="bi bi-bi-linkedin pe-1"></i>
          LinkedIn
          </a>
        </li>
    </ul>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Welcome</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">Preface</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Getting started</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-getting-started.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Getting Started with Data in R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Data Exploration via the tidyverse</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-visualization.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Visualization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-wrangling.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Wrangling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-tidy.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Importing &amp; “Tidy Data”</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">Data Modeling</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Basic Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-multiple-regression.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Multiple Regression</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">Statistical Theory</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-causality.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Randomization and Causality</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-populations.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Populations and Generalizability</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-sampling-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Sampling Distributions</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">Statistical Inference</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-confidence-intervals.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Confidence Intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-p-values.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">P-values</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-hypothesis-tests.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Hypothesis tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-putting-together.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Putting it all together</span></a>
  </div>
</li>
          <li class="px-0"><hr class="sidebar-divider hi "></li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">Appendices</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./statistical-background.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Statistical Background</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#needed-packages" id="toc-needed-packages" class="nav-link active" data-scroll-target="#needed-packages">Needed Packages</a></li>
  <li><a href="#sec-causal-questions" id="toc-sec-causal-questions" class="nav-link" data-scroll-target="#sec-causal-questions"><span class="toc-section-number">7.1</span>  Causal Questions</a></li>
  <li><a href="#sec-randomized-experiments" id="toc-sec-randomized-experiments" class="nav-link" data-scroll-target="#sec-randomized-experiments"><span class="toc-section-number">7.2</span>  Randomized experiments</a>
  <ul class="collapse">
  <li><a href="#random-processes-in-r" id="toc-random-processes-in-r" class="nav-link" data-scroll-target="#random-processes-in-r"><span class="toc-section-number">7.2.1</span>  Random processes in R</a></li>
  </ul></li>
  <li><a href="#sec-omitted-variables" id="toc-sec-omitted-variables" class="nav-link" data-scroll-target="#sec-omitted-variables"><span class="toc-section-number">7.3</span>  Omitted variables</a></li>
  <li><a href="#the-magic-of-randomization" id="toc-the-magic-of-randomization" class="nav-link" data-scroll-target="#the-magic-of-randomization"><span class="toc-section-number">7.4</span>  The magic of randomization</a>
  <ul class="collapse">
  <li><a href="#sec-ed-data" id="toc-sec-ed-data" class="nav-link" data-scroll-target="#sec-ed-data"><span class="toc-section-number">7.4.1</span>  Randomization Example</a></li>
  <li><a href="#estimating-the-treatment-effect" id="toc-estimating-the-treatment-effect" class="nav-link" data-scroll-target="#estimating-the-treatment-effect"><span class="toc-section-number">7.4.2</span>  Estimating the treatment effect</a></li>
  </ul></li>
  <li><a href="#if-you-know-z-what-about-multiple-regression" id="toc-if-you-know-z-what-about-multiple-regression" class="nav-link" data-scroll-target="#if-you-know-z-what-about-multiple-regression"><span class="toc-section-number">7.5</span>  If you know Z, what about multiple regression?</a></li>
  <li><a href="#what-if-you-dont-know-z" id="toc-what-if-you-dont-know-z" class="nav-link" data-scroll-target="#what-if-you-dont-know-z"><span class="toc-section-number">7.6</span>  What if you don’t know Z?</a></li>
  <li><a href="#sec-causality-conclusion" id="toc-sec-causality-conclusion" class="nav-link" data-scroll-target="#sec-causality-conclusion"><span class="toc-section-number">7.7</span>  Conclusion</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/NUstat/intro-stat-data-sci/edit/main/07-causality.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/NUstat/intro-stat-data-sci/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-causality" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Randomization and Causality</span></span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<p>In this chapter we kick off the third segment of this book: statistical theory. Up until this point, we have focused only on descriptive statistics and exploring the data we have in hand. Very often the data available to us is <strong>observational data</strong> – data that is collected via a survey in which nothing is manipulated or via a log of data (e.g., scraped from the web). As a result, any relationship we observe is limited to our specific sample of data, and the relationships are considered <strong>associational</strong>. In this chapter we introduce the idea of making inferences through a discussion of <strong>causality</strong> and <strong>randomization</strong>.</p>
<section id="needed-packages" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="needed-packages">Needed Packages</h3>
<p>Let’s load all the packages needed for this chapter (this assumes you’ve already installed them). If needed, read <a href="01-getting-started.html#sec-packages"><span>Section&nbsp;1.3</span></a> for information on how to install and load R packages.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">

</div>
</section>
<section id="sec-causal-questions" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="sec-causal-questions"><span class="header-section-number">7.1</span> Causal Questions</h2>
<p>What if we wanted to understand not just if X is associated with Y, but if X <strong>causes</strong> Y? Examples of causal questions include:</p>
<ul>
<li>Does <em>smoking</em> cause <em>cancer</em>?</li>
<li>Do <em>after school programs</em> improve student <em>test scores</em>?</li>
<li>Does <em>exercise</em> make people <em>happier</em>?</li>
<li>Does exposure to <em>abstinence only education</em> lead to lower <em>pregnancy rates</em>?</li>
<li>Does <em>breastfeeding</em> increase baby <em>IQs</em>?</li>
</ul>
<p>Importantly, note that while these are all causal questions, they do not all directly use the word <em>cause</em>. Other words that imply causality include:</p>
<ul>
<li>Improve</li>
<li>Increase / decrease</li>
<li>Lead to</li>
<li>Make</li>
</ul>
<p>In general, the tell-tale sign that a question is causal is if the analysis is used to make an argument for changing a procedure, policy, or practice.</p>
</section>
<section id="sec-randomized-experiments" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="sec-randomized-experiments"><span class="header-section-number">7.2</span> Randomized experiments</h2>
<p>The gold standard for understanding causality is the <strong>randomized experiment</strong>. For the sake of this chapter, we will focus on experiments in which people are randomized to one of two conditions: treatment or control. Note, however, that this is just one scenario; for example, schools, offices, countries, states, households, animals, cars, etc. can all be randomized as well, and can be randomized to more than two conditions.</p>
<p>What do we mean by random? Be careful here, as the word “random” is used colloquially differently than it is statistically. When we use the word <strong>random</strong> in this context, we mean:</p>
<ul>
<li>Every person (or unit) has some chance (i.e., a non-zero probability) of being selected into the treatment or control group.</li>
<li>The selection is based upon a <strong>random process</strong> (e.g., names out of a hat, a random number generator, rolls of dice, etc.)</li>
</ul>
<p>In practice, a randomized experiment involves several steps.</p>
<ol type="1">
<li>Half of the sample of people is randomly assigned to the treatment group (T), and the other half is assigned to the control group (C).</li>
<li>Those in the treatment group receive a treatment (e.g., a drug) and those in the control group receive something else (e.g., business as usual, a placebo).</li>
<li>Outcomes (Y) in the two groups are observed for all people.</li>
<li>The effect of the treatment is calculated using a simple regression model, <span class="math display">\[\hat{y} = b_0 + b_1T \]</span> where <span class="math inline">\(T\)</span> equals 1 when the individual is in the treatment group and 0 when they are in the control group. Note that using the notation introduced in <a href="05-regression.html#sec-model2table"><span>Section&nbsp;5.2.2</span></a>, this would be the same as writing <span class="math inline">\(\hat{y} = b_0 + b_1\mathbb{1}_{\mbox{Trt}}(x)\)</span>. We will stick with the <span class="math inline">\(T\)</span> notation for now, because this is more common in randomized experiments in practice.</li>
</ol>
<p>For this simple regression model, <span class="math inline">\(b_1 = \bar{y}_T - \bar{y}_C\)</span> is the observed “treatment effect”, where <span class="math inline">\(\bar{y}_T\)</span> is the average of the outcomes in the treatment group and <span class="math inline">\(\bar{y}_C\)</span> is the average in the control group. This means that the “treatment effect” is simply the difference between the treatment and control group averages.</p>
<section id="random-processes-in-r" class="level3" data-number="7.2.1">
<h3 data-number="7.2.1" class="anchored" data-anchor-id="random-processes-in-r"><span class="header-section-number">7.2.1</span> Random processes in R</h3>
<p>There are several functions in R that mimic random processes. You have already seen one example in <a href="05-regression.html">Chapters&nbsp;<span>5</span></a> and <a href="06-multiple-regression.html"><span>6</span></a> when we used <code>sample_n</code> to randomly select a specifized number of rows from a dataset. The function <code>rbernoulli()</code> is another example, which allows us to mimic the results of a series of random coin flips. The first argument in the <code>rbernoulli()</code> function, <code>n</code>, specifies the number of trials (in this case, coin flips), and the argument <code>p</code> specifies the probability of “success”” for each trial. In our coin flip example, we can define “success” to be when the coin lands on heads. If we’re using a fair coin then the probability it lands on heads is 50%, so <code>p = 0.5</code>.</p>
<p>Sometimes a random process can give results that don’t <em>look</em> random. For example, even though any given coin flip has a 50% chance of landing on heads, it’s possible to observe many tails in a row, just due to chance. In the example below, 10 coin flips resulted in only 3 heads, and the first 7 flips were tails. Note that TRUE corresponds to the notion of “success”, so here TRUE = heads and FALSE = tails.</p>
<div class="cell" data-layout-align="center">

</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>coin_flips <span class="ot">&lt;-</span> <span class="fu">rbernoulli</span>(<span class="at">n =</span> <span class="dv">10</span>, <span class="at">p =</span> <span class="fl">0.5</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>coin_flips</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE  TRUE</code></pre>
</div>
</div>
<p>Importantly, just because the results don’t <em>look</em> random, does not mean that the results <em>aren’t</em> random. If we were to repeat this random process, we will get a different set of random results.</p>
<div class="cell" data-layout-align="center">

</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>coin_flips2 <span class="ot">&lt;-</span> <span class="fu">rbernoulli</span>(<span class="at">n =</span> <span class="dv">10</span>, <span class="at">p =</span> <span class="fl">0.5</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>coin_flips2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  TRUE  TRUE FALSE  TRUE FALSE FALSE  TRUE FALSE FALSE  TRUE</code></pre>
</div>
</div>
<p>Random processes can appear unstable, particularly if they are done only a small number of times (e.g.&nbsp;only 10 coin flips), but if we were to conduct the coin flip procedure thousands of times, we would expect the results to stabilize and see on average 50% heads.</p>
<div class="cell" data-layout-align="center">

</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>coin_flips3 <span class="ot">&lt;-</span> <span class="fu">rbernoulli</span>(<span class="at">n =</span> <span class="dv">100000</span>, <span class="at">p =</span> <span class="fl">0.5</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>coin_flips3 <span class="sc">%&gt;%</span> </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(value) <span class="sc">%&gt;%</span> </span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percent =</span> <span class="dv">100</span> <span class="sc">*</span> n<span class="sc">/</span><span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  value     n percent
  &lt;lgl&gt; &lt;int&gt;   &lt;dbl&gt;
1 FALSE 49879    49.9
2 TRUE  50121    50.1</code></pre>
</div>
</div>
<p>Often times when running a randomized experiment in practice, you want to ensure that exactly half of your participants end up in the treatment group. In this case, you don’t want to flip a coin for each participant, because just by chance, you could end up with 63% of people in the treatment group, for example. Instead, you can imagine each participant having an ID number, which is then randomly sorted or shuffled. You could then assign the first half of the randomly sorted ID numbers to the treatment group, for example. R has many ways of mimicing this type of random assignment process as well, such as the <code>randomizr</code> package.</p>
</section>
</section>
<section id="sec-omitted-variables" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="sec-omitted-variables"><span class="header-section-number">7.3</span> Omitted variables</h2>
<p>In a randomized experiment, we showed in <a href="#sec-randomized-experiments"><span>Section&nbsp;7.2</span></a> that we can calculate the estimated causal effect (<span class="math inline">\(b_1\)</span>) of a treatment using a simple regression model.</p>
<p>Why can’t we use the same model to determine causality with observational data? Recall our discussion from <a href="05-regression.html#sec-correlation-is-not-causation"><span>Section&nbsp;5.3.2</span></a>. We have to be very careful not to make unwarranted causal claims from observational data, because there may be an <strong>omitted variable</strong> (Z), also known as a <strong>confounder</strong>:</p>
<p><img src="images/confounder.png" class="img-fluid"></p>
<p>Here are some examples:</p>
<ul>
<li>There is a positive relationship between sales of ice cream (X) from street vendors and crime (Y). Does this mean that eating ice cream causes increased crime? No.&nbsp;The omitted variable is the season and weather (Z). That is, there is a positive relationship between warm weather (Z) and ice cream consumption (X) and between warm weather (Z) and crime (Y).</li>
<li>Students that play an instrument (X) have higher grades (Y) than those that do not. Does this mean that playing an instrument causes improved academic outcomes? No.&nbsp;Some omitted variables here could be family socio-economic status and student motivation. That is, there is a positive relationship between student motivation (and a family with resources) (Z) and likelihood of playing an instrument (X) and between motivation / resources and student grades (Y).</li>
<li>Countries that eat a lot of chocolate (X) also win the most Nobel Prizes (Y). Does this mean that higher chocolate consumption leads to more Nobel Prizes? No.&nbsp;The omitted variable here is a country’s wealth (Z). Wealthier countries win more Nobel Prizes and also consume more chocolate.</li>
</ul>
<p>Examples of associations that are misinterpreted as causal relationships abound. To see more examples, check out this website: https://www.tylervigen.com/spurious-correlations.</p>
</section>
<section id="the-magic-of-randomization" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="the-magic-of-randomization"><span class="header-section-number">7.4</span> The magic of randomization</h2>
<p>If omitted variables / confounders are such a threat to determining causality in observational data, why aren’t they also a threat in randomized experiments?</p>
<p>The answer is simple: <strong>randomization</strong>. Because people are randomized to treatment and control groups, on average there is no difference between these two groups on any characteristics <em>other than their treatment</em>.</p>
<p>This means that before the treatment is given, on average the two groups (T and C) are equivalent to one another on every observed <em>and</em> unobserved variable. For example, the two groups should be similar in all <strong>pre-treatment</strong> variables: age, gender, motivation levels, heart disease, math ability, etc. Thus, when the treatment is assigned and implemented, any differences between outcomes <em>can be attributed to the treatment</em>.</p>
<section id="sec-ed-data" class="level3" data-number="7.4.1">
<h3 data-number="7.4.1" class="anchored" data-anchor-id="sec-ed-data"><span class="header-section-number">7.4.1</span> Randomization Example</h3>
<p>Let’s see the magic of randomization in action. Imagine that we have a promising new curriculum for teaching math to Kindergarteners, and we want to know whether or not the curriculum is effective. Let’s explore how a randomized experiment would help us test this. First, we’ll load in a dataset called <code>ed_data</code>. This data originally came from the Early Childhood Longitudinal Study (ECLS) program but has been adapted for this example. Let’s take a look at the data.</p>
<div class="cell" data-layout-align="center">

</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>ed_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://docs.google.com/spreadsheets/d/e/2PACX-1vTQ9AvbzZ2DBIRmh5h_NJLpC_b4u8-bwTeeMxwSbGX22eBkKDt7JWMqnuBpAVad6-OXteFcjBY4dGqf/pub?gid=300215043&amp;single=true&amp;output=csv"</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(ed_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 335
Columns: 10
$ ID           &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17…
$ FEMALE       &lt;dbl&gt; 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, …
$ MINORITY     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, …
$ MOM_ED       &lt;chr&gt; "Some college", "Vocational/technical program", "Some col…
$ DAD_ED       &lt;chr&gt; "Vocational/technical program", "Some college", "Bachelor…
$ SES_CONT     &lt;dbl&gt; -0.27, -0.03, 0.48, -0.03, -0.66, 1.53, 0.20, 0.07, -0.32…
$ READ_pre     &lt;dbl&gt; 27.4, 32.5, 48.2, 43.9, 36.1, 95.8, 33.8, 33.1, 32.2, 44.…
$ MATH_pre     &lt;dbl&gt; 18.7, 30.6, 31.6, 31.4, 24.2, 49.8, 27.1, 27.4, 25.1, 41.…
$ Trt_rand     &lt;dbl&gt; 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, …
$ Trt_non_rand &lt;dbl&gt; 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, …</code></pre>
</div>
</div>
<p>It includes information on 335 Kindergarten students: indicator variables for whether they are female or minority students, information on their parents’ highest level of education, a continuous measure of the their socio-economic status (SES), and their reading and math scores. For our purposes, we will assume that these are all <strong>pre-treatment variables</strong> that are measured on students at the beginning of the year, before we conduct our (hypothetical) randomized experiment. We also have included two variables <code>Trt_rand</code> and <code>Trt_non_rand</code> for demonstration purposes, which we will describe below.</p>
<p>In order to conduct our randomized experiment, we could randomly assign half of the Kindergarteners to the treatment group to recieve the new curriculum, and the other half of the students to the control group to recieve the “business as usual” curriculum. <code>Trt_rand</code> is the result of this <em>random assignment</em>, and is an indicator variable for whether the student is in the treatment group (<code>Trt_rand == 1</code>) or the control group (<code>Trt_rand == 0</code>). By inspecting this variable, we can see that 167 students were assigned to treatment and 168 were assigned to control.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>ed_data <span class="sc">%&gt;%</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(Trt_rand)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  Trt_rand     n
     &lt;dbl&gt; &lt;int&gt;
1        0   168
2        1   167</code></pre>
</div>
</div>
<p>Remember that because this treatment assignment was <strong>random</strong>, we don’t expect a student’s treatment status to be correlated with any of their other pre-treatment characteristics. In other words, students in the treatment and control groups should look approximately the same <em>on average</em>. Looking at the means of all the numeric variables by treatment group, we can see that this is true in our example. Note how the <code>summarise_if</code> function is working here; if a variable in the dataset is numeric, then it is summarized by calculating its <code>mean</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>ed_data <span class="sc">%&gt;%</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Trt_rand) <span class="sc">%&gt;%</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_if</span>(is.numeric, mean) <span class="sc">%&gt;%</span> </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(ID, Trt_non_rand))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  Trt_rand FEMALE MINORITY SES_CONT READ_pre MATH_pre
     &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1        0  0.542    0.327    0.296     46.8     39.0
2        1  0.569    0.293    0.320     48.2     39.9</code></pre>
</div>
</div>
<p>Both the treatment and control groups appear to be approximately the same on average on the observed characteristics of gender, minority status, SES, and pre-treatment reading and math scores. Note that since <code>FEMALE</code> is coded as 0 - 1, the “mean” is simply the proportion of students in the dataset that are female. The same is true for <code>MINORITY</code>.</p>
<p>In our hypothetical randomized experiment, after randomizing students into the treatment and control groups, we would then implement the appropriate (new or business as usual) math curriculum throughout the school year. We would then measure student math scores again at the end of the year, and if we observed that the treatment group was scoring higher (or lower) on average than the control group, we could attribute that difference entirely to the new curriculum. We would not have to worry about other omitted variables being the cause of the difference in test scores, because randomization ensured that the two groups were equivalent on average on <em>all</em> pre-treatment characteristics, both observed and unobserved.</p>
<p>In comparison, in an observational study, the two groups are not equivalent on these pre-treatment variables. In the same example above, let us imagine where instead of being randomly assigned to treatment, instead students with lower SES are assigned to the new specialized curriculum (<code>Trt_non_rand = 1</code>), and those with higher SES are assigned to the business as usual curriculum (<code>Trt_non_rand = 0</code>). The indicator variable <code>Trt_non_rand</code> is the result of this non-random treatment group assignment process.</p>
<p>In this case, the table of comparisons between the two groups looks quite different:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>ed_data <span class="sc">%&gt;%</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Trt_non_rand) <span class="sc">%&gt;%</span> </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_if</span>(is.numeric, mean) <span class="sc">%&gt;%</span> </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(ID, Trt_rand))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  Trt_non_rand FEMALE MINORITY SES_CONT READ_pre MATH_pre
         &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1            0  0.565    0.226    0.912     51.7     43.6
2            1  0.545    0.395   -0.300     43.3     35.3</code></pre>
</div>
</div>
<p>There are somewhat large differences between the treatment and control group on several pre-treatment variables in addition to SES (e.g.&nbsp;% minority, and reading and math scores). Notice that the two groups still appear to be balanced in terms of gender. This is because gender is in general not associated with SES. However, minority status and test scores are both correlated with SES, so assigning treatment based on SES (instead of via a random process) results in an imbalance on those other pre-treatment variables. Therefore, if we observed differences in test scores at the end of the year, it would be difficult to disambiguate whether the differences were caused by the intervention or due to some of these other pre-treatment differences.</p>
</section>
<section id="estimating-the-treatment-effect" class="level3" data-number="7.4.2">
<h3 data-number="7.4.2" class="anchored" data-anchor-id="estimating-the-treatment-effect"><span class="header-section-number">7.4.2</span> Estimating the treatment effect</h3>
<p>Imagine that the truth about this new curriculum is that it raises student math scores by 10 points, on average. We can use R to mimic this process and randomly generate post-test scores that raise the treatment group’s math scores by 10 points on average, but leave the control group math scores largely unchanged. Note that we will never know the true treatment effect in real life - the treatment effect is what we’re trying to estimate; this is for demonstration purposes only.</p>
<p>We use another random process function in R, <code>rnorm()</code> to generate these random post-test scores. Don’t worry about understanding exactly how the code below works, just note that in both the <code>Trt_rand</code> and <code>Trt_non_rand</code> case, we are creating post-treatment math scores that increase a student’s score by 10 points on average, if they received the new curriculum.</p>
<div class="cell" data-layout-align="center">

</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>ed_data <span class="ot">&lt;-</span> ed_data <span class="sc">%&gt;%</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">MATH_post_trt_rand =</span> </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>           <span class="fu">case_when</span>(Trt_rand <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> MATH_pre <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, <span class="dv">10</span>, <span class="dv">2</span>), </span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>                     Trt_rand <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> MATH_pre <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">2</span>)),</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">MATH_post_trt_non_rand =</span> </span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>           <span class="fu">case_when</span>(Trt_non_rand <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> MATH_pre <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, <span class="dv">10</span>, <span class="dv">2</span>), </span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>                     Trt_non_rand <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> MATH_pre <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">2</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>By looking at the first 10 rows of this data in <a href="#tbl-post-scores">Table&nbsp;<span>7.1</span></a>, we can convince ourselves that both the <code>MATH_post_trt_rand</code> and <code>MATH_post_trt_non_rand</code> scores reflect this truth that the treatment raises test scores by 10 points, on average. For example, we see that for student 1, they were assigned to the treatment group in both scenarios and their test scores increased from about 18 to about 28. Student 2, however, was only assigned to treatment in the second scenario, and their test scores increased from about 31 to 41, but in the first scenario since they did not receive the treatment, their score stayed at about 31. Remember that here we are showing two hypothetical scenarios that could have occurred for these students - one if they were part of a randomized experiment and one where they were part of an observational study - but in real life, the study would only be conducted one way on the students and not both.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>ed_data <span class="sc">%&gt;%</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ID, MATH_pre, Trt_rand, </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>         MATH_post_trt_rand, Trt_non_rand, </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>         MATH_post_trt_non_rand) <span class="sc">%&gt;%</span> </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ID <span class="sc">&lt;=</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="tbl-post-scores" class="anchored">
<table class="table table-sm table-striped">
<caption>Table&nbsp;7.1: Math scores for first 10 students, under random and non-random treatment assignment scenarios</caption>
<colgroup>
<col style="width: 3%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 25%">
<col style="width: 17%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">ID</th>
<th style="text-align: right;">MATH_pre</th>
<th style="text-align: right;">Trt_rand</th>
<th style="text-align: right;">MATH_post_trt_rand</th>
<th style="text-align: right;">Trt_non_rand</th>
<th style="text-align: right;">MATH_post_trt_non_rand</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">18.7</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">28.4</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">28.9</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">30.6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">31.2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">40.8</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">31.6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">32.2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">31.3</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">31.4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">32.0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">41.6</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">24.2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">34.0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">34.4</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">49.8</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">59.5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">49.5</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">27.1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">27.7</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">37.3</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">27.4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">27.9</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">37.5</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">25.1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">34.9</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">35.3</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">41.9</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">51.6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">41.6</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Let’s examine how students in each group performed on the post-treatment math assessment on average in the first scenario where they were randomly assigned (i.e.&nbsp;using <code>Trt_rand</code> and <code>MATH_post_trt_rand</code>).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>ed_data <span class="sc">%&gt;%</span> </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Trt_rand) <span class="sc">%&gt;%</span> </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">post_trt_rand_avg =</span> <span class="fu">mean</span>(MATH_post_trt_rand))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  Trt_rand post_trt_rand_avg
     &lt;dbl&gt;             &lt;dbl&gt;
1        0              39.6
2        1              49.6</code></pre>
</div>
</div>
<p>Remember that in a randomized experiment, we calculate the treatment effect by simply taking the difference in the group averages (i.e.&nbsp;<span class="math inline">\(\bar{y}_T - \bar{y}_C\)</span>), so here our estimated treatment effect is <span class="math inline">\(49.6 - 39.6 = 10.0\)</span>. Recall that we said this could be estimated using the simple linear regression model <span class="math inline">\(\hat{y} = b_0 + b_1T\)</span>. We can fit this model in R to verify that our estimated treatment effect is <span class="math inline">\(b_1 = 10.0\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(MATH_post_trt_rand <span class="sc">~</span> Trt_rand, <span class="at">data =</span> ed_data)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>fit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = MATH_post_trt_rand ~ Trt_rand, data = ed_data)

Coefficients:
(Intercept)     Trt_rand  
       39.6         10.0  </code></pre>
</div>
</div>
<p>Let’s also look at the post-treatment test scores by group for the non-randomized experiment case.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>ed_data <span class="sc">%&gt;%</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Trt_non_rand) <span class="sc">%&gt;%</span> </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">post_trt_non_rand_avg =</span> <span class="fu">mean</span>(MATH_post_trt_non_rand))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  Trt_non_rand post_trt_non_rand_avg
         &lt;dbl&gt;                 &lt;dbl&gt;
1            0                  43.3
2            1                  45.5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>fit1_non_rand <span class="ot">&lt;-</span> <span class="fu">lm</span>(MATH_post_trt_non_rand <span class="sc">~</span> Trt_non_rand, <span class="at">data =</span> ed_data)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit1_non_rand)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate Std. Error t value  Pr(&gt;|t|)
(Intercept)     43.31      0.871   49.69 4.37e-156
Trt_non_rand     2.18      1.234    1.76  7.89e-02</code></pre>
</div>
</div>
<p>Note that even though the treatment raised student scores by 10 points on average, in the observational case we estimate the treatment effect is <em>much</em> smaller. This is because treatment was confounded with SES and other pre-treatment variables, so we could not obtain an accurate estimate of the treatment effect.</p>
</section>
</section>
<section id="if-you-know-z-what-about-multiple-regression" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="if-you-know-z-what-about-multiple-regression"><span class="header-section-number">7.5</span> If you know Z, what about multiple regression?</h2>
<p>In the previous sections, we made clear that you cannot calculate the causal effect of a treatment using a <em>simple</em> linear regression model unless you have random assignment. What about a <em>multiple</em> regression model?</p>
<p>The answer here is more complicated. We’ll give you an overview, but note that this is a tiny sliver of an introduction and that there is an entire <em>field</em> of methods devoted to this problem. The field is called <strong>causal inference methods</strong> and focuses on the conditions under and methods in which you can calculate causal effects in observational studies.</p>
<p>Recall, we said before that in an observational study, the reason you can’t attribute causality between X and Y is because the relationship is <strong>confounded</strong> by an omitted variable Z. What if we included Z in the model (making it no longer omitted), as in:</p>
<p><span class="math display">\[\hat{y} = b_0 + b_1T + b_2Z\]</span> As we learned in <a href="06-multiple-regression.html"><span>Chapter&nbsp;6</span></a>, we can now interpret the coefficient <span class="math inline">\(b_1\)</span> as <strong>the estimated effect of the treatment on outcomes, holding constant (or adjusting for) Z</strong>.</p>
<p>Importantly, the relationship between T and Y, adjusting for Z can be similar or different than the relationship between T and Y alone. In advance, you simply cannot know one from the other.</p>
<p>Let’s again look at our model <code>fit1_non_rand</code> that looked at the relationship between treatment and math scores, and compare it to a model that adjusts for the confounding variable SES.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>fit1_non_rand <span class="ot">&lt;-</span> <span class="fu">lm</span>(MATH_post_trt_non_rand <span class="sc">~</span> Trt_non_rand, <span class="at">data =</span> ed_data)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit1_non_rand)<span class="sc">$</span>coefficients</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>fit2_non_rand <span class="ot">&lt;-</span> <span class="fu">lm</span>(MATH_post_trt_non_rand <span class="sc">~</span> Trt_non_rand <span class="sc">+</span> SES_CONT, <span class="at">data =</span> ed_data)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit2_non_rand)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate Std. Error t value  Pr(&gt;|t|)
(Intercept)     43.31      0.871   49.69 4.37e-156
Trt_non_rand     2.18      1.234    1.76  7.89e-02</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)     38.22       1.49   25.73        0
Trt_non_rand     8.93       2.02    4.43        0
SES_CONT         5.57       1.34    4.17        0</code></pre>
</div>
</div>
<p>The two models give quite different indications of how effective the treatment is. In the first model, the estimate of the treatment effect is 2.176, but in the second model once we control for SES, the estimate is 8.931. Again, this is because in our non-random assignment scenario, treatment status was confounded with SES.</p>
<p>Importantly, in the randomized experiment case, controlling for confounders using a multiple regression model is <strong>not</strong> necessary - again, because of the randomization. Let’s look at the same two models using the data from the experimental case (i.e.&nbsp;using <code>Trt_rand</code> and <code>MATH_post_trt_rand</code>).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>fit1_rand_exp <span class="ot">&lt;-</span> <span class="fu">lm</span>(MATH_post_trt_rand <span class="sc">~</span> Trt_rand, <span class="at">data =</span> ed_data)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit1_rand_exp)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error t value  Pr(&gt;|t|)
(Intercept)     39.6      0.928   42.65 5.46e-137
Trt_rand        10.0      1.314    7.64  2.26e-13</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>fit2_rand_exp <span class="ot">&lt;-</span> <span class="fu">lm</span>(MATH_post_trt_rand <span class="sc">~</span> Trt_rand <span class="sc">+</span> SES_CONT, <span class="at">data =</span> ed_data)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit2_rand_exp)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std. Error t value  Pr(&gt;|t|)
(Intercept)    37.68      0.883   42.67 7.98e-137
Trt_rand        9.89      1.205    8.21  5.11e-15
SES_CONT        6.37      0.798    7.98  2.37e-14</code></pre>
</div>
</div>
<p>We can see that both models give estimates of the treatment effect that are roughly the same (10.044 and 9.891), regardless of whether or not we control for SES. This is because randomization ensured that the treatment and control group were balanced on all pre-treatment characteristics - including SES, so there is no need to control for them in a multiple regression model.</p>
</section>
<section id="what-if-you-dont-know-z" class="level2" data-number="7.6">
<h2 data-number="7.6" class="anchored" data-anchor-id="what-if-you-dont-know-z"><span class="header-section-number">7.6</span> What if you don’t know Z?</h2>
<p>In the observational case, if you <em>know</em> the process through which people are assigned to or select treatment then the above multiple regression approach can get you pretty close to the causal effect of the treatment on the outcomes. This is what happened in our <code>fit2_non_rand</code> model above where we knew treatment was determined by SES, and so we controlled for it in our model.</p>
<p>But this is <strong>rarely</strong> the case. In most studies, selection of treatment is <strong>not based on a single variable</strong>. That is, before treatment occurs, those that will ultimately receive the treatment and those that do not might differ in a myriad of ways. For example, students that play instruments may not only come from families with more resources and have higher motivation, but may also play fewer sports, already be great readers, have a natural proclivity for music, or come from a musical family. As an analyst, it is typically very difficult – if not impossible – to know how and why some people selected a treatment and others did not.</p>
<p>Without randomization, here is the best approach:</p>
<ol type="1">
<li>Remember: your goal is to approximate a random experiment. You want the two groups to be similar on any and all variables that are related to uptake of the treatment and the outcome.</li>
<li>Think about the treatment selection process. Why would people choose to play an instrument (or not)? Attend an after-school program (or not)? Be part of a sorority or fraternity (or not)?</li>
<li>Look for variables in your data that you can use in a multiple regression to control for these other possible confounders. Pay attention to how your estimate of the treatment impact changes as you add these into your model (often it will decrease).</li>
<li>State very clearly the assumptions you are making, the variables you have controlled for, and the possible other variables you were unable to control for. Be tentative in your conclusions and make clear their limitations – that this work is suggestive and that future research – a randomized experiment – would be more definitive.</li>
</ol>
</section>
<section id="sec-causality-conclusion" class="level2" data-number="7.7">
<h2 data-number="7.7" class="anchored" data-anchor-id="sec-causality-conclusion"><span class="header-section-number">7.7</span> Conclusion</h2>
<p>In this chapter we’ve focused on the role of randomization in our ability to make inferences – here about causation. As you will see in the next few chapters, randomization is also important for making inferences from outcomes observed in a sample to their values in a population. But the importance of randomization goes even deeper than this – one could say that <strong>randomization is at the core of inferential statistics</strong>.</p>
<p>In situations in which treatment is <strong>randomly assigned</strong> or a sample is <strong>randomly selected</strong> from a population, as a result of <strong>knowing this mechanism</strong>, we are able to imagine and explore alternative realities – what we will call <strong>counter-factual thinking</strong> (<a href="09-sampling-distributions.html"><span>Chapter&nbsp;9</span></a>) – and form ways of understanding when “effects” are likely (or unlikely) to be found simply by chance – what we will call <strong>proof by stochastic contradiction</strong> (<a href="11-p-values.html"><span>Chapter&nbsp;11</span></a>).</p>
<p>Finally, we would be remiss to end this chapter without including this XKCD comic, which every statistician loves:</p>
<p><img src="images/causation.png" class="img-fluid"></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./06-multiple-regression.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Multiple Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./08-populations.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Populations and Generalizability</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>